Rename fold constructors in Data.Fold
composewell/streamly pull request #1028
Opened 2021-04-06 09:39 UTC by rnjtranjan

Fix #1016

2021-04-06 16:43 UTC, harendra-kumar requested changes

2021-04-06 16:43 UTC, harendra-kumar commented on src/Streamly/Data/Fold.hs
> +foldl' = mkFoldl
We should rename `mkFoldl` itself rather than defining a new function.

2021-04-06 18:20 UTC, harendra-kumar requested changes

2021-04-06 18:20 UTC, harendra-kumar commented on src/Streamly/Internal/Data/Fold.hs
>      , mkFoldrM
We can change `mkFoldl1` to `foldl1` and `mkFoldrM` to `foldrM` at the same time. Only `mkFold` and `mkFold_` should remain unchanged.

2021-04-07 07:34 UTC, adithyaov approved these changes

2021-04-07 08:07 UTC, adithyaov commented
@rnjtranjan Can you fix up the initial commits?

2021-04-07 12:10 UTC, harendra-kumar requested changes

2021-04-07 12:10 UTC, harendra-kumar commented on src/Streamly/Internal/Data/Fold.hs
> +    , foldl1
I am sorry, this had to be `foldl1'` instead. The same as we have in "Streamly.Prelude".

2021-04-12 07:30 UTC, harendra-kumar approved these changes

2021-04-12 07:31 UTC, merged