Implement common FS events
composewell/streamly pull request #1197
Opened 2021-08-11 06:31 UTC by rnjtranjan

2021-08-31 10:08 UTC, rnjtranjan commented
Fixes #865

2021-09-08 05:01 UTC, rnjtranjan commented
working on Mac XXX comments.

2021-09-28 04:21 UTC, harendra-kumar commented on src/Streamly/Internal/FileSystem/Event.hs
> +    ]
This is not right, it makes the defaultConfig of windows module different than what `watch` is using, which is terrible. We should set the flags in the `defaultConfig` of the windows module.

2021-09-28 08:33 UTC, harendra-kumar requested changes
I think we should remove watchWithFlags and watchRecursiveWithFlags. Instead the Config can be used to set these flags and `watchWith` will behave according to the config supplied.

2021-09-28 08:51 UTC, harendra-kumar requested changes

2021-09-28 08:51 UTC, harendra-kumar commented on test/Streamly/Test/FileSystem/Event.hs
> +                  fmap fromJust $ S.head $ eventStream `S.parallelFst` fsOps
The code in the "else" part is common with the "if" branch, you can just pass `fp` or `fp ++ "SymLink".`

2021-10-01 04:37 UTC, rnjtranjan commented
All event types except below has been tested:
IN_UNMOUNT
IN_Q_OVERFLOW
IN_ONLYDIR
IN_DONT_FOLLOW
IN_MASK_ADD
IN_ONESHOT

2021-11-14 12:51 UTC, harendra-kumar commented
merged via #1328

2021-11-14 12:51 UTC, closed without merging