Add strip API to  Foreign Array
composewell/streamly pull request #1260
Opened 2021-10-06 07:05 UTC by rnjtranjan

Fix for #1254

2022-03-10 18:41 UTC, harendra-kumar requested changes
This is based on very old commit, the array type has changed since. Can you rebase and fix?

Can you write a basic test for it?

2022-03-10 18:41 UTC, harendra-kumar commented on src/Streamly/Internal/Data/Array/Foreign/Mut/Type.hs
> +            else getLast $ q `plusPtr` negate (sizeOf (undefined :: a))
Use the macros from ArrayMacros.h to manipulate the pointers.

2022-03-10 18:41 UTC, harendra-kumar commented on src/Streamly/Internal/Data/Array/Foreign/Mut/Type.hs
> +    in go st end
`go` is not a recursive function. We can inline the definition right here, that would be more readable.

2022-03-10 18:41 UTC, harendra-kumar commented on src/Streamly/Internal/Data/Array/Foreign/Mut/Type.hs
> +    let p = unsafeForeignPtrToPtr aStart
We will need a `touch` to ensure the pointer is not garbage collected.

2022-03-10 18:41 UTC, harendra-kumar commented on src/Streamly/Internal/Data/Array/Foreign/Mut/Type.hs
> +            st' <- st
The action `st` is being called at two places, we are effectively searching for start twice, instead we can call it once and use the result.

2022-03-11 10:55 UTC, harendra-kumar commented
Can you add a benchmark as well?

2022-03-14 05:52 UTC, rnjtranjan reviewed
Looks good.

2022-03-14 06:11 UTC, merged