Fix A.fromList crashes on empty list of type [()]
composewell/streamly pull request #1353
Opened 2021-11-26 10:11 UTC by rnjtranjan

2021-11-26 12:14 UTC, rnjtranjan commented
fixes #755

2021-11-26 23:34 UTC, adithyaov commented on src/Streamly/Internal/Data/Array/Foreign/Mut/Type.hs
> +    let elemSize = max 1 $ sizeOf x
When can `sizeOf` something be `0`?

2021-11-28 05:15 UTC, rnjtranjan commented on src/Streamly/Internal/Data/Array/Foreign/Mut/Type.hs
> +    let elemSize = max 1 $ sizeOf x
sizeOf  "()" is zero.

2021-11-30 10:30 UTC, harendra-kumar commented
This is not completely fixed. We need to replace all places where `sizeOf` is being used. We can create an internal `sizeOfElem` wrapper over `sizeOf` and use that at all places wherever we are using `sizeOf`.

2022-01-05 08:26 UTC, harendra-kumar requested changes

2022-01-05 08:26 UTC, harendra-kumar commented on src/Streamly/Internal/System/IO.hs
> +byteArrayOverhead = 2 * sizeOfElem (undefined :: Word)
revert this.

2022-01-05 08:26 UTC, harendra-kumar commented on test/Streamly/Test/Common/Array.hs
> +allocOverhead = 2 * sizeOfElem (undefined :: Int)
revert this.

2022-01-05 08:26 UTC, harendra-kumar commented on test/Streamly/Test/FileSystem/Handle.hs
> +allocOverhead = 2 * sizeOfElem (undefined :: Int)
revert this.

2022-01-05 08:26 UTC, harendra-kumar commented on src/Streamly/Internal/Wrapper.hs
> +sizeOfElem _ = max 1 $ ST.sizeOf (undefined :: a)
We can define this in Data.Array.Foreign.Mut.Type. This is array specific and not a general API.

2022-01-05 08:26 UTC, harendra-kumar commented on src/Streamly/Internal/Wrapper.hs
> +sizeOfPrimElem _ = max 1 $ sizeOf (undefined :: a)
We can define this in the lowest level prim array module.

2022-01-06 14:23 UTC, rnjtranjan commented on src/Streamly/Internal/Data/Array/Stream/Foreign.hs
> +                         end1 = end `plusPtr` negate (m * SIZE_OF(a))
May be we can create a macro for this

2022-01-06 14:23 UTC, rnjtranjan reviewed
looks good

2022-01-06 19:05 UTC, merged