Fix inappropriate type (Not a directory) error in Linux for File path…
composewell/streamly pull request #1357
Opened 2021-11-27 11:23 UTC by rnjtranjan

…s in recursive mode

Fix for #1307

2021-11-27 12:59 UTC, harendra-kumar requested changes
Can you also enable the commented test for the case when root path is a file?

2021-11-27 12:59 UTC, harendra-kumar commented on src/Streamly/Internal/FileSystem/Event/Windows.hs
> +-- Use 'watchTrees'or 'watchPaths' with a list of file system dir paths you
We no longer have these APIs. We have `watch` and `watchRecursive`.

2021-11-27 15:40 UTC, rnjtranjan commented
> 

For windows test for the case when root path is a file is not valid as windows API doesn't support it.
For Linux nested file create event times out due to the event is lost.

2021-11-30 11:08 UTC, rnjtranjan reviewed
Looks good

2021-11-30 12:17 UTC, merged