Implement modifyIndices
composewell/streamly pull request #1390
Opened 2021-12-27 14:46 UTC by rnjtranjan

2021-12-27 18:22 UTC, harendra-kumar approved these changes

2021-12-28 02:59 UTC, harendra-kumar requested changes

2021-12-28 02:59 UTC, harendra-kumar commented on src/Streamly/Internal/Data/Array/Foreign/Mut/Type.hs
> +    D.foldlM' func (return ()) str
We can use `modifyIndex` itself to implement this. If you can write a benchmark we can check if there is any difference in perf if at all, I do not see any reason for that though.

2021-12-30 10:04 UTC, rnjtranjan reviewed
looks good.

2021-12-30 10:15 UTC, merged