Fix performance regressions in GHC-9
composewell/streamly pull request #1430
Opened 2022-01-26 17:44 UTC by harendra-kumar

See #1061, #1066, #1067, #1068, #1428 .

There were several fixes in GHC mentioned in the issues above.

The type of fixes required in streamly are:

* INLINE annotation added in a few cases, or INLINABLE converted to INLINE
* INLINE pragma was swapped in mutually recursive cases (deciding the loop breaker)
* Remove NOINLINE from some benchmarks
* Fuse annotation added in one case

There are still some cases remaining to be fixed.

2022-02-02 00:45 UTC, adithyaov commented on src/Streamly/Internal/Data/Parser/ParserD/Type.hs
> +    {-# INLINE handleCollect #-}
This should be `runCollectorWith`?

2022-02-02 00:46 UTC, adithyaov commented on src/Streamly/Internal/Data/Parser/ParserD/Type.hs
> +    {-# INLINE handleCollect #-}
`runCollectorWith`?

2022-02-02 00:46 UTC, adithyaov commented on src/Streamly/Internal/Data/Parser/ParserD/Type.hs
> +    {-# INLINE handleCollect #-}
`runCollectorWith`?

2022-02-02 00:47 UTC, adithyaov commented on src/Streamly/Internal/Data/Parser/ParserD.hs
> +    {-# INLINE scrutR #-}
`scrutL`?

2022-02-02 00:48 UTC, adithyaov requested changes
Can fix the comments? The rest looks good.

2022-02-04 20:44 UTC, closed without merging

2022-02-05 18:51 UTC, harendra-kumar commented
Got closed accidentally, I will open another one.