Change the signature of array getIndices
composewell/streamly pull request #1437
Opened 2022-02-02 15:13 UTC by rnjtranjan

2022-02-02 17:46 UTC, harendra-kumar requested changes

2022-02-02 17:46 UTC, harendra-kumar commented on src/Streamly/Internal/Data/Array/Foreign/Mut/Type.hs
> +    D.Stream m Int -> Unfold m (Array a) a
This should be `SerialT m Int`.

2022-02-02 17:46 UTC, harendra-kumar commented on src/Streamly/Internal/Data/Array/Foreign.hs
> +getIndices (SerialT stream) = MA.getIndices $ D.fromStreamK stream
This is immutable array module, this API should use the immutable array type, not `MA.Array`.

2022-02-03 15:15 UTC, rnjtranjan commented
Fixes : #1402

2022-02-03 15:41 UTC, harendra-kumar requested changes

2022-02-03 15:41 UTC, harendra-kumar commented on src/Streamly/Internal/Data/Array/Foreign.hs
> +getIndices (SerialT stream) = getIndices' $ D.fromStreamK stream
Just use unsafeFreeze/unsafeThaw to convert mutable/immutable arrays, do not duplicate the code.

2022-02-10 04:00 UTC, harendra-kumar commented
It would be nice to have a test as well, we can copy the takeWhile test if it exists.

2022-02-10 04:02 UTC, merged