Add a test for wAsync behavior check
composewell/streamly pull request #1447
Opened 2022-02-03 15:09 UTC by rnjtranjan

2022-02-03 15:11 UTC, rnjtranjan commented
Fixes: #1224

2022-02-03 17:34 UTC, adithyaov commented on test/lib/Streamly/Test/Prelude/Common.hs
> +constructfromWAsync s1 s2 res =
Can you also check the asyncness of the code?
An `IORef` to capture the effects would work.
```
gen i = threadDelay i >> addToIORefStuff >> return i
```
Then you can use `fromListM` and check the IORef for the expected order of effects.

2022-02-10 04:35 UTC, harendra-kumar requested changes

2022-02-10 04:35 UTC, harendra-kumar commented on test/Streamly/Test/Prelude/Async.hs
> +            constructfromAsyncNThread 4 2 [2,4]
This is already being at line 127 below using `parallelCheck`. We can remove it.

2022-02-10 04:35 UTC, harendra-kumar commented on test/lib/Streamly/Test/Prelude/Common.hs
> +        equals (==) x res
We can move this code to WAsync test module itself as this is specific to wAsync and not common.

2022-02-10 04:35 UTC, harendra-kumar commented on test/lib/Streamly/Test/Prelude/Common.hs
> +        equals (==) x res
We can move this code to Async test module itself as this is specific to Async and not common.

2022-02-11 01:00 UTC, merged