Add a routine that tees a parser with a fold
composewell/streamly pull request #1487
Opened 2022-02-19 20:37 UTC by adithyaov

This is an interesting routine where we can perform some kind of
metrics on the parser.

The motivation for this is routines like,
```
uncons :: Utf8 -> (Char, Utf8)
```

Given,
```
parseCharUtf8 :: Parser m Word8 Char
length :: Fold m a Int
```

We can efficiently implement `uncons` like so,
```
uncons x = do
  (c, i) <- parse (teeFold (,) parseCharUtf8 length) (toStream x)
  return (c, getSlice i (len x - i) x
```

A general possibility of easily running some kind of metrics on
parsers can be useful. I have not thought about it but this might
be a replacement for backtracking folds.

2022-02-19 20:38 UTC, adithyaov commented
We should decide on the name. Thec current combinator should probably be called `teeWithFoldMin`.

2022-02-19 21:04 UTC, adithyaov commented
The benchmarks look good!

2022-02-21 03:22 UTC, harendra-kumar requested changes

2022-02-21 03:22 UTC, harendra-kumar commented on src/Streamly/Internal/Data/Parser/ParserD/Tee.hs
> +                              ++ "is not extractable."
Why not extract and let the parser raise the error. Parser knows the best whether it can be extracted or not.

2022-02-21 03:22 UTC, harendra-kumar commented on src/Streamly/Internal/Data/Parser/ParserD/Tee.hs
> +       Monad m => (a -> b -> c) -> Parser m x a -> Fold m x b -> Parser m x c
The backtracking behavior is not consistent. The parser backtracks but fold does not backtrack, so the fold may consume the input multiple times.

One possibility is to use it for non-backtracking parsers only and raise an error on backtracking.

Also note that we can downgrade a parser to a fold and use it in Fold tee operation. In that case an error will be generated on backtracking or on parser Error.

What is the used case for this? I can understand it better by looking at the use case.

2022-03-15 10:28 UTC, closed without merging