Change the signature/impl of demuxDefaultWith fold
composewell/streamly pull request #1503
Opened 2022-03-06 06:23 UTC by rnjtranjan

2022-03-06 06:25 UTC, rnjtranjan commented
Fixes: #1495

2022-03-08 12:07 UTC, harendra-kumar requested changes

2022-03-09 06:41 UTC, harendra-kumar requested changes

2022-03-09 06:41 UTC, harendra-kumar commented on src/Streamly/Internal/Data/Fold.hs
> --}
We can keep this comment, this is a TODO.

2022-03-09 06:41 UTC, harendra-kumar commented on src/Streamly/Internal/Data/Fold.hs
> -demuxWith f kv = fmap fst $ demuxDefaultWith f kv drain
We can remove this and rename `demuxDefaultWith` to `demuxWith`.

2022-03-09 06:41 UTC, harendra-kumar commented on src/Streamly/Internal/Data/Fold.hs
> +
Why are these moved after classify? We can put these right after demuxDefaultWith.

2022-03-09 06:41 UTC, harendra-kumar commented on src/Streamly/Internal/Data/Fold.hs
> +
We can remove `demux_`.

2022-03-09 09:37 UTC, harendra-kumar requested changes

2022-03-09 09:37 UTC, harendra-kumar commented on src/Streamly/Internal/Data/Fold.hs
> +        res <- dstep dacc a
Previous review comment regarding this state is not addressed.

2022-03-09 10:18 UTC, harendra-kumar requested changes

2022-03-09 10:18 UTC, harendra-kumar commented on src/Streamly/Internal/Data/Fold.hs
> +                    doneMap runMap fd k a
This has become ugly. 1) Although all folds in runMap are done we are not directly going to DemuxOnlyDefault state, we are running the default fold in this state only 2) only if the default fold returns Done then we will go to DemuxOnlyDefault State.

2022-03-09 10:18 UTC, harendra-kumar commented on src/Streamly/Internal/Data/Fold.hs
> +                    return (Done doneMap)
Why are we terminating the fold here? There may be more data in the stream for default handler.

2022-03-09 10:18 UTC, harendra-kumar commented on src/Streamly/Internal/Data/Fold.hs
> +                | isNothing finished ->
We already know that the fold is running, it is found in the runMap, then why are we checking whether the fold is done?

2022-03-09 10:18 UTC, harendra-kumar commented on src/Streamly/Internal/Data/Fold.hs
> +                    return (Done doneMap)
Since it is already running, it will not be found in the doneMap, so we will always terminate here.

We need a test for demux.

2022-03-14 06:05 UTC, rnjtranjan commented
Fixes : #1494

2022-03-14 06:06 UTC, rnjtranjan commented
Fixes: #1495

2022-04-29 08:57 UTC, closed without merging