Remove Deprecated Modules
composewell/streamly pull request #1507
Opened 2022-03-08 06:27 UTC by rnjtranjan

2022-03-08 08:08 UTC, harendra-kumar commented
We should remove only after at least two major releases of deprecation that means it has to be deprecated in 0.7 and 0.8, then we can remove in 0.9.

We can remove Streamly.Internal.Data.Time module for example because it remained deprecated in 0.7 and 0.8.

2022-03-09 07:46 UTC, harendra-kumar commented
As I said earlier, we should not remove too early. We should remove only if the modules/functions were deprecated in 0.7 or earlier. Many of the functions removed in this PR were deprecated only in 0.8.

2022-03-10 06:06 UTC, harendra-kumar requested changes
I do not see Streamly or Streamly.Data.Unicode.Stream or Streamly.Memory.Array being deprecated in 0.7.0.

2022-03-10 06:06 UTC, harendra-kumar commented on src/Streamly/Internal/Data/Stream/IsStream/Transform.hs
> --- accommodate this.
We can keep this TODO comment.

2022-03-10 06:06 UTC, harendra-kumar commented
Please rebase to resolve the conflicts.

2022-03-10 19:24 UTC, harendra-kumar requested changes

2022-03-10 19:24 UTC, harendra-kumar commented on src/Streamly/Memory/Array.hs
> +import Streamly.Internal.Data.Array.Foreign as A
This file should not have any change, should be reverted.

2022-03-10 19:24 UTC, harendra-kumar commented
Please squash the changes.

2022-03-11 08:10 UTC, harendra-kumar commented
Can we add a changelog entry, saying removal of function deprecated in or before 0.7.0?

2022-03-14 06:01 UTC, rnjtranjan commented
Fixes: #1477

2022-03-14 06:24 UTC, harendra-kumar commented on docs/Changelog.md
> +## 0.9.0 (Mar 2022)
We use "Unreleased" here instead of 0.9.0 .

2022-03-22 19:38 UTC, harendra-kumar commented
It seems many are still running 0.7.x, so let's remove only those that were deprecated in or before 0.6 .

2022-03-23 06:57 UTC, closed without merging

2022-03-23 06:57 UTC, rnjtranjan commented
opened another PR : https://github.com/composewell/streamly/pull/1552