Rename a few APIs in FileSystem.Handle module
composewell/streamly pull request #1524
Opened 2022-03-14 12:45 UTC by rnjtranjan

2022-03-14 12:46 UTC, rnjtranjan commented
Fixes: #1168

2022-03-14 18:07 UTC, harendra-kumar requested changes

2022-03-14 18:07 UTC, harendra-kumar commented on src/Streamly/Internal/FileSystem/Handle.hs
>      , toChunks
Should be `getChunks` and `getChunksWith`.

2022-03-19 12:14 UTC, harendra-kumar requested changes
Deprecate the released functions instead of changing them.

2022-03-20 08:16 UTC, harendra-kumar requested changes
Only those functions that have been released, should be deprecated. See https://streamly.composewell.com/haddocks/streamly-0.8.2/Streamly-FileSystem-Handle.html for released functions.

2022-03-24 15:58 UTC, harendra-kumar requested changes

2022-03-24 15:58 UTC, harendra-kumar commented on src/Streamly/FileSystem/Handle.hs
> +    , readWith
`readBufferOf` should be kept with deprecation. And same for other released functions as well.

2022-03-25 08:34 UTC, merged