Add benchmark and Test for scan of Unfold
composewell/streamly pull request #1534
Opened 2022-03-16 08:44 UTC by rnjtranjan

2022-03-16 08:48 UTC, rnjtranjan commented
Fixes : #1313

2022-03-19 12:48 UTC, harendra-kumar requested changes

2022-03-19 12:48 UTC, harendra-kumar commented on test/Streamly/Test/Data/Unfold.hs
> +                  _x = _list :: [Int]
This looks ugly, why is `_list` even being passed as argument? Why is `_fA` required.

2022-03-19 12:54 UTC, harendra-kumar commented on test/Streamly/Test/Data/Unfold.hs
> +                  mList = [1,3,6,10] :: [Int]
Can we use the passed list instead and compare it against the Data.List scan function?

2022-03-24 17:53 UTC, harendra-kumar requested changes

2022-03-24 17:53 UTC, harendra-kumar commented on test/Streamly/Test/Data/Unfold.hs
> +                  mList = scanl1 (+) ls
Looks like `UF.scan` should be renamed to `UF.postscan`.

Also, I noticed that `UF.scanlM'` is marked as `Unimplemented` even though it is implemented. We can fix that too. Also. UF.scanlM' should be renamed as `postscanlM'`.

Also, rename this test as `postscan`.

2022-03-25 09:49 UTC, merged