add scanMnay for Unfold
composewell/streamly pull request #1537
Opened 2022-03-17 06:29 UTC by rnjtranjan

2022-03-17 09:54 UTC, rnjtranjan commented
Fixes: #1308

2022-03-30 13:09 UTC, harendra-kumar requested changes

2022-03-30 13:09 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Unfold.hs
> +                                    Skip (Nothing, Nothing)
This is unnecessarily complicated, why not just say return `Stop` here? The `Maybe` is not required on the first element of the tuple.

2022-03-30 13:09 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Unfold.hs
> +                                    Skip (Nothing, Nothing)
Better would be to just change `scan` to `scanWith` and pass a flag to it to stop or restart the scan. Then use the same common function of scan and scanMany.

2022-04-01 09:43 UTC, harendra-kumar requested changes

2022-04-01 09:43 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Unfold.hs
> +
Remove blank line.

2022-04-01 09:43 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Unfold.hs
> +            FL.Done _ -> return (Nothing, Nothing)
This is not correct, we need to yield the result before we stop.

2022-04-11 05:25 UTC, harendra-kumar requested changes

2022-04-11 05:25 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Unfold.hs
> +                return (Just (fs, x), Nothing)
A scan always yields the initial value. This is not correct. Can you write a test for this?

2022-04-29 10:51 UTC, merged