Add ScanMany for Stream
composewell/streamly pull request #1539
Opened 2022-03-17 09:53 UTC by rnjtranjan

2022-03-17 09:54 UTC, rnjtranjan commented
Fixes: #1308

2022-04-11 05:41 UTC, harendra-kumar requested changes

2022-04-11 05:41 UTC, harendra-kumar commented on src/Streamly/Internal/Data/Stream/IsStream/Transform.hs
> +-- scan = P.scanOnce
Remove this comment.

2022-04-11 05:41 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Stream/StreamD/Transform.hs
> +                            then return $ Yield b (ScanDo s fs, Just b)
I do not understand the point of keeping the second element of state tuple. This is unnecessarily complicated. All we need to do is unconditionally reinit the scan on done if the `restart` flag is true.

2022-04-29 10:50 UTC, merged