Drop 8.0 to 8.2.0 GHC Support
composewell/streamly pull request #1543
Opened 2022-03-17 17:26 UTC by rnjtranjan

2022-03-17 17:30 UTC, rnjtranjan commented
Fixes: #927

2022-03-18 09:41 UTC, rnjtranjan commented
GHC 8.2.2 build fails,  need help to fix it.

2022-03-19 13:18 UTC, harendra-kumar requested changes
This looks mostly incorrect. Looks like the code that was valid for newer compilers has been removed. Please review.

Also, the CIs for 8.0.x and 8.2.x should be removed.

2022-03-19 13:18 UTC, harendra-kumar commented on core/src/Streamly/Internal/BaseCompat.hs
> -import qualified GHC.Exts as GHCExt
These lines should be kept unconditionally.

2022-03-19 13:18 UTC, harendra-kumar commented on core/src/Streamly/Internal/BaseCompat.hs
> -#endif
These should be removed.

2022-03-19 13:18 UTC, harendra-kumar commented on core/src/Streamly/Internal/BaseCompat.hs
>  #endif
This should be removed.

2022-03-20 06:00 UTC, harendra-kumar requested changes
Still looks mostly incorrect changes.

Consider code like this:

```
#if MIN_VERSION_base(4,10,0)
code
#endif
```

This means if base is at least 4.10.0 . After removing GHC 8.2 and lower we always have base at least 4.10. So the above code should be kept unconditionally instead of removing it.

2022-03-21 10:16 UTC, harendra-kumar requested changes

2022-03-21 10:16 UTC, harendra-kumar commented on benchmark/lib/Streamly/Benchmark/Prelude.hs
> +#endif
This has to be removed. This means GHC versions <= 8.2.x which we are not supporting any more.

2022-03-21 10:16 UTC, harendra-kumar commented on core/src/Streamly/Internal/BaseCompat.hs
> +#endif
The `#if` condition has to be removed, here and at other places as well. base is always >= 4.10 now.

2022-03-21 13:06 UTC, harendra-kumar commented on src/Streamly/Internal/Data/SmallArray/Type.hs
> -
Should be kept.

2022-03-21 13:07 UTC, harendra-kumar commented on test/Streamly/Test/Data/Parser.hs
> +    case S.parse (P.die err) (S.fromList [0 :: Int]) of
should be `fail`.

2022-03-21 15:33 UTC, rnjtranjan commented on core/src/Streamly/Internal/Data/Parser/ParserK/Type.hs
> -
MIN_VERSION_base will  be always >= (4,10,0)
then it will never execute?

2022-03-21 18:36 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Parser/ParserK/Type.hs
> -
It seems you still have an incorrect understanding of the macro. `#if MIN_VERSION_base` means - this code block is enabled as long as the `base` version is 4.9.0 or more. So if base version is 4.10, 4.11, 4.12... this code will be enabled.

2022-03-24 05:35 UTC, merged