Create Type module for Serial Stream
composewell/streamly pull request #1615
Opened 2022-05-12 11:27 UTC by rnjtranjan

2022-05-16 07:49 UTC, harendra-kumar requested changes

2022-05-16 07:49 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Stream/Serial/Transform.hs
> +-- XXX We should only export generation and combinators from this module.
Remove this line.

2022-05-16 07:49 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Stream/Serial/Generate.hs
> +TRAVERSABLE_INSTANCE(SerialT)
Instances should be in the same file as the type to avoid orphan instances.

2022-05-16 07:49 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Stream/Serial/Eliminate.hs
> +LIST_INSTANCES(SerialT)
Move to where the type is defined.

2022-05-18 06:50 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Stream/Serial/Type.hs
> +-- Module      : Streamly.Internal.Data.Stream.Serial
Fix module name.

2022-05-18 06:50 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Stream/Serial.hs
> +( module Streamly.Internal.Data.Stream.Serial.Type)
Add file header.

2022-05-18 06:50 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Stream/Serial/Type.hs
> +-- License     : BSD3
BSD-3-Clause

2022-05-18 06:54 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Stream/Serial/Eliminate.hs
> +module Streamly.Internal.Data.Stream.Serial.Eliminate
Add file header.

2022-05-18 06:54 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Stream/Serial/Eliminate.hs
> +drain :: Monad m => SerialT m a -> m ()
Add the same documentation as in Streamly.Prelude (i.e. Streamly.Internal.Data.Stream.IsStream).
Add all the docs in a separate commit.

2022-05-29 03:22 UTC, rnjtranjan commented
a new PR is created: https://github.com/composewell/streamly/pull/1642

2022-05-29 03:22 UTC, closed without merging