Change pollCount signature
composewell/streamly pull request #1652
Opened 2022-06-04 13:25 UTC by rnjtranjan

2022-06-06 03:08 UTC, rnjtranjan commented
Fixes: https://github.com/composewell/streamly/issues/1651

2022-06-10 16:45 UTC, harendra-kumar requested changes

2022-06-10 16:45 UTC, harendra-kumar commented on benchmark/Streamly/Benchmark/Prelude/Serial/Transformation.hs
> +    f = S.drain . Internal.delayPost 1
Don't remove rollingMap2, we need to do some processing on the stream to get a realistic code.

2022-06-22 09:00 UTC, harendra-kumar approved these changes
Squash the commits

2022-07-04 12:34 UTC, merged