Move nubwindowby to the Fold.Window module
composewell/streamly pull request #1659
Opened 2022-06-05 13:01 UTC by rnjtranjan

2022-06-09 09:53 UTC, rnjtranjan commented
Fixes:https://github.com/composewell/streamly/issues/1529

2022-06-10 17:19 UTC, harendra-kumar requested changes
Can you remove the pollCounts change from this?

2022-06-10 17:36 UTC, harendra-kumar requested changes

2022-06-10 17:36 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Fold/Window.hs
> +                Just a -> Set.delete a set `seq` Set.insert new set
BUG 1: the delete is ineffective as you are inserting the new element in the original set in which the element is not deleted.

BUG 2: The element can be deleted from the Set only when the last reference of that element inside the current window is removed. We talked about this earlier, I had suggested to  use a refcount and decrement the refcount when an element is removed from the window, the element can be removed from the set when the refcount reaches 0.

2022-06-22 09:14 UTC, harendra-kumar requested changes

2022-06-22 09:14 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Fold/Window.hs
> +    , nub
This is not the right place to add it. Add it in a separate section at the end.

2022-06-22 09:14 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Fold/Window.hs
> +        return $ Partial (Set.empty, Map.empty)
Do not use both a Set and a Map. Just the Map should be enough. Make the signature of the function as:

```
nub :: (Monad m, Ord a) => Fold m (a, Maybe a) (Map a Int)
```

We can just return a Map of values and their refcounts. The users can use it in whatever way they want.

2022-06-27 10:54 UTC, harendra-kumar requested changes

2022-06-27 10:54 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Fold/Window.hs
> +                        m3 =
Rename to `m2`.

2022-06-27 10:54 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Fold/Window.hs
> +                                    else Map.adjust (\x -> x - 1) a m1
use a single `alterF` operation instead of using two operations (lookup and adjust).

2022-06-27 10:54 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Fold/Window.hs
> +                                _ -> m1
This should never occur, we should use an error statement here to indicate a bug.

2022-06-27 10:54 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Fold/Window.hs
> +                Nothing -> Map.insertWith (+) new (1::Int) map0
This statement is common in Just and Nothing case, so we can factor this out.

2022-07-05 09:24 UTC, merged