Make stuff work with unpinned
composewell/streamly pull request #1697
Opened 2022-06-29 09:19 UTC by adithyaov

2022-06-29 09:58 UTC, adithyaov commented on core/src/Streamly/Internal/Data/Array/Foreign/Mut/Type.hs
> +newAlignedArrayContents :: Int -> Int -> IO (ArrayContents a, Int)
`(ArrayContents a, Int)` can be changed to `ArrayContents a`

2022-07-01 11:47 UTC, adithyaov commented
```
Streamly/Benchmark/Unicode/Stream.hs:213:1: copyStreamLatin1' `hasNoType` Streamly.Internal.Data.Stream.StreamD.Step.Step failed:
Streamly/Benchmark/Unicode/Stream.hs:214:1: copyStreamLatin1' `hasNoType` Streamly.Internal.Data.Unfold.Type.ConcatState failed:
Streamly/Benchmark/Unicode/Stream.hs:215:1: copyStreamLatin1' `hasNoType` Streamly.Internal.Data.Array.Foreign.Mut.Type.ReadUState failed:
Streamly/Benchmark/Unicode/Stream.hs:217:1: copyStreamLatin1' `hasNoType` Streamly.Internal.Data.Fold.Step.Step failed:
Streamly/Benchmark/Unicode/Stream.hs:218:1: copyStreamLatin1' `hasNoType` Streamly.Internal.Data.Array.Foreign.Mut.Type.ArrayUnsafe failed:
Streamly/Benchmark/Unicode/Stream.hs:234:1: copyStreamLatin1 `hasNoType` Streamly.Internal.Data.Stream.StreamD.Step.Step failed:
Streamly/Benchmark/Unicode/Stream.hs:235:1: copyStreamLatin1 `hasNoType` Streamly.Internal.Data.Unfold.Type.ConcatState failed:
Streamly/Benchmark/Unicode/Stream.hs:236:1: copyStreamLatin1 `hasNoType` Streamly.Internal.Data.Array.Foreign.Mut.Type.ReadUState failed:
Streamly/Benchmark/Unicode/Stream.hs:238:1: copyStreamLatin1 `hasNoType` Streamly.Internal.Data.Fold.Type.ManyState failed:
Streamly/Benchmark/Unicode/Stream.hs:239:1: copyStreamLatin1 `hasNoType` Streamly.Internal.Data.Fold.Step.Step failed:
Streamly/Benchmark/Unicode/Stream.hs:240:1: copyStreamLatin1 `hasNoType` Streamly.Internal.Data.Array.Foreign.Mut.Type.ArrayUnsafe failed:

Streamly/Benchmark/Prelude/Serial/Exceptions.hs:130:1: readWriteOnExceptionStream does not contain dictionary values failed:
Streamly/Benchmark/Prelude/Serial/Exceptions.hs:141:1: readWriteHandleExceptionStream does not contain dictionary values failed:
Streamly/Benchmark/Prelude/Serial/Exceptions.hs:151:1: readWriteFinally_Stream does not contain dictionary values failed:
Streamly/Benchmark/Prelude/Serial/Exceptions.hs:167:1: fromToBytesBracket_Stream does not contain dictionary values failed:
Streamly/Benchmark/Prelude/Serial/Exceptions.hs:184:1: readWriteBeforeAfterStream `hasNoType` Streamly.Internal.Data.Stream.StreamD.Step.Step failed:
Streamly/Benchmark/Prelude/Serial/Exceptions.hs:193:1: readWriteAfterStream `hasNoType` Streamly.Internal.Data.Stream.StreamD.Step.Step failed:
Streamly/Benchmark/Prelude/Serial/Exceptions.hs:202:1: readWriteAfter_Stream does not contain dictionary values failed:
Streamly/Benchmark/Prelude/Serial/Exceptions.hs:203:1: readWriteAfter_Stream `hasNoType` Streamly.Internal.Data.Stream.StreamD.Step.Step failed:
Streamly/Benchmark/Prelude/Serial/Exceptions.hs:243:1: readChunksOnException does not contain dictionary values failed:
Streamly/Benchmark/Prelude/Serial/Exceptions.hs:253:1: readChunksBracket_ does not contain dictionary values failed:
Streamly/Benchmark/Prelude/Serial/Exceptions.hs:287:1: toChunksBracket_ does not contain dictionary values failed:

Streamly/Benchmark/Prelude/Serial/Split.hs:67:1: splitOn does not contain dictionary values failed:
Streamly/Benchmark/Prelude/Serial/Split.hs:68:1: splitOn `hasNoType` Streamly.Internal.Data.Stream.StreamD.Step.Step passed.
Streamly/Benchmark/Prelude/Serial/Split.hs:69:1: splitOn `hasNoType` Streamly.Internal.Data.Unfold.Type.ConcatState passed.
Streamly/Benchmark/Prelude/Serial/Split.hs:70:1: splitOn `hasNoType` Streamly.Internal.Data.Array.Foreign.Mut.Type.ReadUState passed.
Streamly/Benchmark/Prelude/Serial/Split.hs:80:1: splitOnSuffix does not contain dictionary values failed:
Streamly/Benchmark/Prelude/Serial/Split.hs:81:1: splitOnSuffix `hasNoType` Streamly.Internal.Data.Stream.StreamD.Step.Step passed.
Streamly/Benchmark/Prelude/Serial/Split.hs:82:1: splitOnSuffix `hasNoType` Streamly.Internal.Data.Unfold.Type.ConcatState passed.
Streamly/Benchmark/Prelude/Serial/Split.hs:83:1: splitOnSuffix `hasNoType` Streamly.Internal.Data.Array.Foreign.Mut.Type.ReadUState passed.
Streamly/Benchmark/Prelude/Serial/Split.hs:93:1: splitWithSuffix does not contain dictionary values failed:
Streamly/Benchmark/Prelude/Serial/Split.hs:94:1: splitWithSuffix `hasNoType` Streamly.Internal.Data.Stream.StreamD.Step.Step passed.
Streamly/Benchmark/Prelude/Serial/Split.hs:95:1: splitWithSuffix `hasNoType` Streamly.Internal.Data.Unfold.Type.ConcatState passed.
Streamly/Benchmark/Prelude/Serial/Split.hs:96:1: splitWithSuffix `hasNoType` Streamly.Internal.Data.Array.Foreign.Mut.Type.ReadUState passed.
Streamly/Benchmark/Prelude/Serial/Split.hs:124:1: wordsBy does not contain dictionary values failed:
Streamly/Benchmark/Prelude/Serial/Split.hs:125:1: wordsBy `hasNoType` Streamly.Internal.Data.Stream.StreamD.Step.Step failed:
Streamly/Benchmark/Prelude/Serial/Split.hs:126:1: wordsBy `hasNoType` Streamly.Internal.Data.Unfold.Type.ConcatState failed:
Streamly/Benchmark/Prelude/Serial/Split.hs:127:1: wordsBy `hasNoType` Streamly.Internal.Data.Array.Foreign.Mut.Type.ReadUState failed:

Streamly/Benchmark/FileSystem/Handle/Read.hs:239:1: chunksOf `hasNoType` Streamly.Internal.Data.Array.Foreign.Mut.Type.ReadUState passed.
Streamly/Benchmark/FileSystem/Handle/Read.hs:238:1: chunksOf `hasNoType` Streamly.Internal.Data.Unfold.Type.ConcatState passed.
Streamly/Benchmark/FileSystem/Handle/Read.hs:237:1: chunksOf `hasNoType` Streamly.Internal.Data.Array.Foreign.Mut.Type.ArrayUnsafe passed.
Streamly/Benchmark/FileSystem/Handle/Read.hs:236:1: chunksOf `hasNoType` Streamly.Internal.Data.Stream.StreamD.Type.FoldMany passed.
Streamly/Benchmark/FileSystem/Handle/Read.hs:235:1: chunksOf `hasNoType` Streamly.Internal.Data.Stream.StreamD.Step.Step passed.
Streamly/Benchmark/FileSystem/Handle/Read.hs:234:1: chunksOf does not contain dictionary values failed:
Streamly/Benchmark/FileSystem/Handle/Read.hs:197:1: getChunksConcatUnfoldCountLines `hasNoType` Streamly.Internal.Data.Stream.StreamD.Type.ConcatMapUState passed.
Streamly/Benchmark/FileSystem/Handle/Read.hs:196:1: getChunksConcatUnfoldCountLines `hasNoType` Streamly.Internal.Data.Stream.StreamD.Step.Step passed.
Streamly/Benchmark/FileSystem/Handle/Read.hs:195:1: getChunksConcatUnfoldCountLines does not contain dictionary values failed:
Streamly/Benchmark/FileSystem/Handle/Read.hs:150:1: readDecodeUtf8 does not contain dictionary values failed:
Streamly/Benchmark/FileSystem/Handle/Read.hs:119:1: readSumBytes `hasNoType` Streamly.Internal.Data.Array.Foreign.Mut.Type.ReadUState passed.
Streamly/Benchmark/FileSystem/Handle/Read.hs:118:1: readSumBytes `hasNoType` Streamly.Internal.Data.Unfold.Type.ConcatState passed.
Streamly/Benchmark/FileSystem/Handle/Read.hs:117:1: readSumBytes `hasNoType` Streamly.Internal.Data.Stream.StreamD.Step.Step passed.
Streamly/Benchmark/FileSystem/Handle/Read.hs:116:1: readSumBytes does not contain dictionary values failed:
Streamly/Benchmark/FileSystem/Handle/Read.hs:107:1: readCountWords does not contain dictionary values failed:
Streamly/Benchmark/FileSystem/Handle/Read.hs:95:1: readCountLines `hasNoType` Streamly.Internal.Data.Array.Foreign.Mut.Type.ReadUState passed.
Streamly/Benchmark/FileSystem/Handle/Read.hs:94:1: readCountLines `hasNoType` Streamly.Internal.Data.Unfold.Type.ConcatState passed.
Streamly/Benchmark/FileSystem/Handle/Read.hs:93:1: readCountLines `hasNoType` Streamly.Internal.Data.Stream.StreamD.Step.Step passed.
Streamly/Benchmark/FileSystem/Handle/Read.hs:92:1: readCountLines does not contain dictionary values failed:
Streamly/Benchmark/FileSystem/Handle/Read.hs:80:1: readCountBytes `hasNoType` Streamly.Internal.Data.Array.Foreign.Mut.Type.ReadUState passed.
Streamly/Benchmark/FileSystem/Handle/Read.hs:79:1: readCountBytes `hasNoType` Streamly.Internal.Data.Unfold.Type.ConcatState passed.
Streamly/Benchmark/FileSystem/Handle/Read.hs:78:1: readCountBytes `hasNoType` Streamly.Internal.Data.Stream.StreamD.Step.Step passed.
Streamly/Benchmark/FileSystem/Handle/Read.hs:77:1: readCountBytes does not contain dictionary values failed:
Streamly/Benchmark/FileSystem/Handle/Read.hs:68:1: readLast `hasNoType` Streamly.Internal.Data.Array.Foreign.Mut.Type.ReadUState passed.
Streamly/Benchmark/FileSystem/Ha [...]

2022-07-01 12:10 UTC, adithyaov commented
Benchmarks that need to be checked:
```
decode-encode/encodeLatin1' . decodeLatin1
decode-encode/encodeLatin1 . decodeLatin1

exceptions/S.onException
exceptions/S.handle
exceptions/S.finally_
exceptions/S.bracket_
exceptions/S.after . S.before
exceptions/S.after
exceptions/S.after_

exceptions/readChunks/UF.onException
exceptions/readChunks/UF.bracket_

exceptions/toChunks/S.bracket_

split/S.splitOn (== lf) FL.drain
split/S.splitWithSuffix (== lf) FL.drain
split/S.splitWithSuffixSeq \"\\r\\n\" FL.drain
split/S.wordsBy isSpace FL.drain

reduce/read/chunks/S.chunksOf 1
reduce/read/chunks/S.chunksOf 10
reduce/read/chunks/S.chunksOf 1000

reduce/toBytes/US.lines . SS.decodeLatin1

reduce/read/SS.decodeUtf8
reduce/read/S.length
reduce/read/US.lines . SS.decodeLatin1
reduce/read/US.words . SS.decodeLatin1
reduce/read/S.last
reduce/read/S.sum

copy/FH.write . FH.read
copy/FH.writeWith . FH.readWith

copy/putBytes/FH.readWith
copy/putBytes/rawToNull

copy/read/rawToFile
copy/read/rawToNull

copy/getChunks/toNull
copy/getChunks/raw

exceptions/UF.onException
exceptions/UF.handle
exceptions/UF.finally_
exceptions/UF.bracket_

reduce/toChunks/Stream.last
reduce/toChunks/Stream.sum . Stream.map Array.length
reduce/toChunks/countBytes
reduce/toChunks/decodeUtf8Arrays
reduce/toChunks/splitOnSuffix
reduce/toChunks/splitOn

copy/toChunks/group-ungroup/interposeSuffix . splitOnSuffix
copy/toChunks/group-ungroup/interpose . splitOn
```

2022-07-06 05:39 UTC, adithyaov commented on core/src/Streamly/Internal/Data/Ring/Foreign.hs
> +unsafeEqArray Ring{..} rh arr@(A.Array{..}) =
We should be able to compare it with an unpinned array as well.

2022-07-06 05:39 UTC, adithyaov commented on core/src/Streamly/Internal/Data/Ring/Foreign.hs
> +unsafeEqArrayN Ring{..} rh arr@(A.Array{..}) n =
We should be able to compare it with an unpinned array as well.

2022-07-08 11:05 UTC, adithyaov commented on core/src/Streamly/Internal/Data/Array/Foreign/Mut/Type.hs
> +reallocAligned elemSize alignSize newCapacityInBytes Array{..} = do
Please look at this a little more carefully.

2022-07-08 11:05 UTC, adithyaov commented on core/src/Streamly/Internal/Data/Array/Foreign/Mut/Type.hs
> +    let oldSize = aEnd arr - arrStart arr
Little more careful review.

2022-07-08 11:05 UTC, adithyaov commented on core/src/Streamly/Internal/Data/Array/Foreign/Mut/Type.hs
> +        len = aEnd - start
Little more careful review.

2022-07-08 11:06 UTC, adithyaov commented on core/src/Streamly/Internal/Data/Array/Foreign/Mut/Type.hs
> +    let start1 = arrStart arr1
Careful review.

2022-07-08 11:06 UTC, adithyaov commented on core/src/Streamly/Internal/Data/Array/Foreign/Mut/Type.hs
> +         let startSrc = arrStart src
Careful review.

2022-07-08 11:06 UTC, adithyaov commented on core/src/Streamly/Internal/Data/Array/Foreign/Mut/Type.hs
> +    let sizeB = SIZE_OF(b)
Careful review

2022-07-08 11:07 UTC, adithyaov commented on core/src/Streamly/Internal/Data/Array/Foreign/Mut/Type.hs
> +    liftIO
Careful review

2022-07-08 11:15 UTC, adithyaov commented on core/src/Streamly/Internal/Data/Ring/Foreign.hs
> +unsafeEqArrayN Ring{..} rh arr@(A.Array{..}) n =
We should always peek and compare?

2022-07-14 07:41 UTC, harendra-kumar requested changes
I have added a commit with review comments.

2022-07-18 20:49 UTC, adithyaov commented on core/src/Streamly/Internal/Data/Unboxed.hs
> +    -- Read an element of type "a" from a Ptr given the element index.
Now that we use elements, it's pretty weird to use `Ptr` to consider element index.

2022-07-18 20:56 UTC, adithyaov commented on src/Streamly/Internal/Unicode/Stream.hs
> +-- XXX We can just use Foreign.Storable in this.
We could, but there was a specific reason for changing this, which I seem to have forgotten. Either way, better to use one class for unboxed representation.

2022-07-27 14:49 UTC, closed without merging