Add API to generate Stream from memory Address
composewell/streamly pull request #1730
Opened 2022-07-22 12:32 UTC by rnjtranjan

fixes:https://github.com/composewell/streamly/issues/1729

2022-07-27 09:56 UTC, adithyaov commented on core/src/Streamly/Internal/Data/Stream/Generate.hs
> +ptrtoStreamK = go
This should be in `StreamK` and should be called `fromPtrN` or `fromPtrNUnsafe`

2022-07-27 09:59 UTC, adithyaov commented on core/src/Streamly/Internal/Data/Stream/Generate.hs
> +    Stream.fromStreamK $ ptrtoStreamK (castPtr $ Ptr addr) n
`$` inside `(` `)` looks weird. Maybe,
```suggestion
    Stream.fromStreamK $ ptrtoStreamK (castPtr (Ptr addr)) n
```

2022-07-27 09:59 UTC, adithyaov commented on core/src/Streamly/Internal/Data/Stream/Generate.hs
> +fromAddrN# :: forall m a. (MonadIO m, Storable a) =>
Add `Inline` statement

2022-08-03 10:46 UTC, harendra-kumar requested changes

2022-08-03 10:46 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Stream/Generate.hs
> +import Foreign.Storable (Storable)
Sort order.

2022-08-03 10:46 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Stream/StreamD/Generate.hs
> +  where
indent by 4 spaces and add a blank line after this.

2022-08-03 10:46 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Stream/StreamD/Generate.hs
> +import Foreign.Ptr (Ptr, plusPtr)
sort order.

2022-08-03 10:46 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Stream/Generate.hs
> +-- XXX Should we rename this to fromPtrNUnsafe?
When you are dealing with Ptrs you know what you are doing. We can add a warning in the docs.

2022-08-03 10:46 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Stream/Generate.hs
> +ptrtoStreamK p = D.toStreamK . D.fromPtrN p
Remove this.

2022-08-03 10:46 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Stream/Generate.hs
> +fromPtrN n ptr = Stream.fromStreamK $ ptrtoStreamK ptr n
This should be simply `Stream.fromStreamD . D.fromPtrN n`

2022-08-03 10:46 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Stream/Generate.hs
> +    Stream.fromStreamK $ ptrtoStreamK (Ptr addr) n
This should be simply `fromPtrN n (Ptr addr)`. Define this after fromPtrN.

2022-08-04 20:03 UTC, harendra-kumar requested changes

2022-08-04 20:03 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Stream/StreamD/Generate.hs
> +fromPtrN n0 p0 = Stream step (p0, n0)
Let's implement this as an unfold as well, in the Unfold module.

2022-08-07 06:01 UTC, rnjtranjan reviewed
looks good.

2022-08-08 10:20 UTC, merged