Move Streamly.data.Unfold to core
composewell/streamly pull request #1771
Opened 2022-08-11 03:41 UTC by rnjtranjan

2022-08-17 07:30 UTC, harendra-kumar requested changes
Need to update the changelog as well.

2022-08-17 07:30 UTC, harendra-kumar commented on src/Streamly/Internal/Data/Stream/IsStream/Unfold.hs
> +where
A module only for this looks like an overkill. Can it be moved to IsStream.Generate instead?

2022-08-17 07:30 UTC, harendra-kumar commented on src/Streamly/Internal/Data/Stream/IsStream/Unfold.hs
> +-- /Since: 0.8.0/
We will have to change the since notation, as this is new to this module.

2022-08-18 09:56 UTC, rnjtranjan commented
Fixes:https://github.com/composewell/streamly/issues/1750

2022-08-19 05:54 UTC, harendra-kumar reviewed
squash the commits to ready for merge.

2022-08-19 05:54 UTC, harendra-kumar commented on src/Streamly/Internal/Data/Stream/IsStream/Generate.hs
> +unfoldFromStream = Unfold.lmap IsStream.toStream Unfold.fromStreamK
We can call this as `readStream` to keep it shorter.

2022-08-20 04:29 UTC, rnjtranjan reviewed
Looks fine.

2022-08-20 05:29 UTC, merged