Make streamly-core free from IsStream
composewell/streamly pull request #1796
Opened 2022-08-21 07:20 UTC by rnjtranjan

2022-08-22 06:37 UTC, harendra-kumar requested changes
I will make minor changes and push it.

2022-08-22 06:37 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Fold/Type.hs
> +-- >>> import qualified Streamly.Prelude as PStream
The convention is to import it as IsStream, that way we can also find it easily to replace later.

2022-08-22 06:42 UTC, harendra-kumar commented
Can you also replace the instances of `Streamly.Prelude` imports with `Streamly.Data.Stream`?

2022-08-23 04:52 UTC, rnjtranjan commented
Currently, WserialT and ZipSerialT are wrapped on StreamK that need to be on Stream.

2022-08-23 06:34 UTC, harendra-kumar reviewed
Some imports are out of order, some may be redundant e.g. importing Streamly.Data.Stream as well as Streamly.Internal.Data.Stream. This is not mandatory to fix though, but a nice to have.

2022-08-23 06:34 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Stream/StreamD/Nesting.hs
> +-- wSerial"
Remove this. This is already present in Streamly.Internal.Data.Stream, we do not want duplication.

2022-08-23 09:41 UTC, merged