Reduce Internal module imports from streamly-core
composewell/streamly pull request #1830
Opened 2022-09-08 10:12 UTC by rnjtranjan

2022-09-13 12:19 UTC, harendra-kumar requested changes

2022-09-15 04:58 UTC, rnjtranjan commented
Fixes:https://github.com/composewell/streamly/issues/1815

2022-09-15 09:54 UTC, harendra-kumar requested changes

2022-09-15 09:54 UTC, harendra-kumar commented on src/Streamly/Internal/FileSystem/Dir.hs
> +import qualified Streamly.Internal.Data.Unfold as UF (mapM2, map)
use `fmap` instead of `map`.

2022-09-19 21:18 UTC, merged