Remove IsStream import from FileSystem.Event.* modules
composewell/streamly pull request #1849
Opened 2022-09-21 07:54 UTC by rnjtranjan

Fixes:https://github.com/composewell/streamly/issues/1839

2022-09-22 08:49 UTC, adithyaov requested changes
Added a review commit

2022-09-22 10:30 UTC, harendra-kumar requested changes

2022-09-22 10:30 UTC, harendra-kumar commented on src/Streamly/Internal/FileSystem/Event/Linux.hs
> +        mapM'_ (addToWatch cfg watch0 root . appendPaths path)
Use `Fold.drainBy`.

2022-09-22 10:30 UTC, harendra-kumar commented on src/Streamly/Internal/FileSystem/Event/Windows.hs
> +    S.concatMap S.fromList $ repeatM
Use `repeat` followed by `sequence`.

2022-09-22 10:30 UTC, harendra-kumar commented on src/Streamly/Internal/FileSystem/Event/Windows.hs
> +closePathHandleStream = mapM'_ (\(h, _, _) -> closeHandle h)
Use `Fold.drainBy`.

2022-09-26 11:15 UTC, harendra-kumar commented on src/Streamly/Internal/FileSystem/Event/Linux.hs
> +mapM'_ f = S.fold (FL.drainBy f)
Use this code directly instead of creating the mapM_ wrapper function.

2022-09-26 11:15 UTC, harendra-kumar commented on src/Streamly/Internal/FileSystem/Event/Windows.hs
> +mapM'_ f = S.fold (Fold.drainBy f)
Use the code directly instead of writing the wrapper function.

2022-09-26 11:18 UTC, harendra-kumar commented on src/Streamly/Internal/FileSystem/Event/Windows.hs
> +repeatM = S.sequence . S.repeat
Use this code directly, remove the intermediate repeatM.

2022-09-28 20:39 UTC, harendra-kumar approved these changes

2022-09-28 20:39 UTC, merged