Move Streamly.FileSystem.Handle to streamly-core
composewell/streamly pull request #1854
Opened 2022-09-22 16:50 UTC by rnjtranjan

2022-09-23 04:51 UTC, rnjtranjan commented
fixes:https://github.com/composewell/streamly/issues/1835

2022-09-26 12:53 UTC, harendra-kumar requested changes

2022-09-26 12:53 UTC, harendra-kumar commented on core/src/Streamly/Internal/FileSystem/Handle.hs
> +    => Int -> Handle -> S.Stream m (Array Word8)
Use the `Stream` type unqualified.

2022-09-26 12:53 UTC, harendra-kumar commented on core/src/Streamly/Internal/FileSystem/Handle.hs
> +mapM'_ f = D.mapM_ f . S.toStreamD
Use `drainBy`.

2022-09-26 12:53 UTC, harendra-kumar commented on core/streamly-core.cabal
> +
remove one blank line.

2022-09-26 12:53 UTC, harendra-kumar commented on src/Streamly/Internal/FileSystem/File.hs
> +import Streamly.Data.Stream (Stream)
The changes in this file are already made in another PR.

2022-09-26 12:53 UTC, harendra-kumar commented on core/streamly-core.cabal
> +                      , Streamly.FileSystem.Handle
This should go in the exposed modules section below.

2022-09-26 12:53 UTC, harendra-kumar commented on core/src/Streamly/Internal/FileSystem/Handle.hs
> +import qualified Streamly.Internal.Data.Array.Stream.Mut.Foreign as AS
Let's move `Streamly.Internal.Data.Array.Stream.Foreign` to `streamly-core` in a separate PR, and then base this PR on that one.

2022-09-26 12:53 UTC, harendra-kumar commented on core/src/Streamly/Internal/FileSystem/Handle.hs
> +concat' m = S.fromStreamD $ D.unfoldMany A.read (S.toStreamD m)
Let's move Array.Stream.Foreign to streamly-core and use it from there.

2022-09-29 16:05 UTC, merged