Rename one to next
composewell/streamly pull request #1872
Opened 2022-09-29 06:56 UTC by rnjtranjan

2022-09-30 07:52 UTC, harendra-kumar requested changes

2022-09-30 07:52 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Parser.hs
> +-}
Remove this.

2022-09-30 07:52 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Fold.hs
> +-- {-# DEPRECATED head "Please use \"next\" instead" #-}
We can uncomment this line to actually deprecate this.

2022-10-03 12:15 UTC, rnjtranjan commented
A new PR : https://github.com/composewell/streamly/pull/1887 has been created.

2022-10-03 12:15 UTC, closed without merging