Expose Unicode.Char.Parser
composewell/streamly pull request #1878
Opened 2022-09-30 08:21 UTC by rnjtranjan

2022-09-30 12:21 UTC, adithyaov commented on core/src/Streamly/Unicode/Char/Parser.hs
> +    -- digits
Make this a heading?

2022-09-30 12:21 UTC, adithyaov commented
@harendra-kumar 
1. Do we want to expose all the APIs?
2. We need to add more docs if we are exposing it. Maybe some examples.

2022-10-03 11:06 UTC, harendra-kumar requested changes
As discussed, rename the module to Streamly.Unicode.Parser.

2022-10-03 12:52 UTC, harendra-kumar requested changes
Change "print" to "printable".

2022-10-03 14:25 UTC, adithyaov commented on core/src/Streamly/Unicode/Parser.hs
> +    -- * Numeric
This should be `Numbers`

2022-10-03 14:25 UTC, adithyaov commented on core/src/Streamly/Unicode/Parser.hs
> +    , numeric
This should be under `Digit`

2022-10-03 14:29 UTC, adithyaov reviewed
Please address the comments.

2022-10-03 14:36 UTC, adithyaov commented
Fixed the comments.

2022-10-04 07:22 UTC, adithyaov commented on core/src/Streamly/Internal/Unicode/Char/Parser.hs
> +-- predicates to Streamly.Unicode.Parser.Latin1.
What is `Unicode.Parser.Latin1`? Where should `Latin1` stuff go in? @harendra-kumar

2022-10-04 11:23 UTC, merged