And a Concurrent Zip Applicative  type  in Data.Stream.Zip.Concurrent module
composewell/streamly pull request #1954
Opened 2022-10-14 06:11 UTC by rnjtranjan

2022-10-14 06:14 UTC, rnjtranjan commented
Fixes: https://github.com/composewell/streamly/issues/1942

2022-10-14 13:28 UTC, harendra-kumar requested changes

2022-10-14 13:28 UTC, harendra-kumar commented on src/Streamly/Internal/Data/Stream/Zip/ConcurrentZip.hs
> +        ConcurrentZipM $ fmap f m
We can derive the Functor instance.

2022-10-15 04:44 UTC, rnjtranjan commented on src/Streamly/Internal/Data/Stream/Zip/ConcurrentZip.hs
> +{-# LANGUAGE UndecidableInstances #-}
The constraint ‘Control.Monad.Trans.Control.MonadBaseControl
                    IO m’
    is no smaller than
    the instance head ‘Applicative (ZipConcurrent m)’
  (Use UndecidableInstances to permit this)
• In the instance declaration for ‘Applicative (ZipConcurrent m)’

2022-10-15 11:30 UTC, harendra-kumar requested changes

2022-10-15 11:30 UTC, harendra-kumar commented on src/Streamly/Internal/Data/Stream/Zip/Concurrent.hs
> +        deriving (Semigroup, Monoid, Functor)
Rather than using the Semigroup/Monoid of the Serial stream we may want to use concurrent versions of those. Remove these two instances.

2022-10-15 11:30 UTC, harendra-kumar commented on src/Streamly/Internal/Data/Stream/Zip/Concurrent.hs
> +{-# LANGUAGE UndecidableInstances #-}
Is this required?

2022-10-17 05:56 UTC, adithyaov commented
@harendra-kumar Can we deprecate `Streamly.Internal.Data.Stream.ZipAsync` in favor of this?
Also `Stream.Zip.Concurrent` vs `Stream.Concurrent.Zip`

2022-10-17 06:01 UTC, adithyaov commented
We shouldn't be adding this module.
We should be moving `Streamly.Internal.Data.Stream.ZipAsync` to `Streamly.InternalData.Stream.Zip.Concurrent` and change stuff accordingly instead.
That was we track what is being changed.

2022-10-18 10:42 UTC, harendra-kumar requested changes

2022-10-18 10:42 UTC, harendra-kumar commented on src/Streamly/Internal/Data/Stream/Zip/Concurrent.hs
> +newtype ZipConcurrent m a = ZipConcurrent {getStream :: Stream m a}
Rename `getStream` to `getZipConcurrent`.

2022-10-18 17:24 UTC, merged