Add repeatM to Streamly.Data.Stream module
composewell/streamly pull request #1957
Opened 2022-10-14 12:14 UTC by rnjtranjan

Fixes:https://github.com/composewell/streamly/issues/1919

2022-10-14 12:23 UTC, adithyaov commented on core/src/Streamly/Data/Stream.hs
> +    , repeatM
We only want to add it to an `Internal` module. We don't want to expose it.

2022-10-14 12:23 UTC, adithyaov requested changes
Don't release `repeatM`

2022-10-15 11:41 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Stream/Generate.hs
> +repeatM = Stream.sequence . repeat
Add the documentation from Streamly.Prelude.

2022-10-18 11:02 UTC, harendra-kumar requested changes

2022-10-18 17:28 UTC, merged