Rename rights, lefts, both
composewell/streamly pull request #2139
Opened 2022-11-24 06:11 UTC by rnjtranjan

2022-11-25 10:59 UTC, rnjtranjan commented
Fixes:https://github.com/composewell/streamly/issues/2135

2022-11-30 09:41 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Fold/Type.hs
> +-- | Remove the either wrapper and flatten both catLefts and as well as catRights in
```suggestion
-- | Remove the either wrapper and flatten both lefts and as well as rights in
```

2022-11-30 09:41 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Parser/ParserD/Type.hs
> +-- Folds can only return the right values. Parsers can also return catLefts.
```suggestion
-- Folds can only return the right values. Parsers can also return lefts.
```

2022-11-30 09:41 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Stream/Expand.hs
> +-- Keep concating either streams as long as catRights are generated, stop as soon
```suggestion
-- Keep concating either streams as long as rights are generated, stop as soon
```

2022-11-30 09:41 UTC, harendra-kumar commented on src/Streamly/Internal/Data/Stream/IsStream/Expand.hs
> +-- Keep concating either streams as long as catRights are generated, stop as soon
```suggestion
-- Keep concating either streams as long as rights are generated, stop as soon
```

2022-11-30 09:41 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Stream/Transform.hs
> +-- | Remove the either wrapper and flatten catEithers catLefts and as well as catRights in
```suggestion
-- | Remove the either wrapper and flatten both lefts and as well as rights in
```

2022-11-30 11:20 UTC, harendra-kumar approved these changes

2022-12-01 07:37 UTC, harendra-kumar requested changes

2022-12-01 07:37 UTC, harendra-kumar commented on src/Streamly/Internal/FileSystem/Event/Darwin.hs
> +    S.rights $ S.parseMany readOneEvent $ S.unfold FH.reader handle
We should remove the import of import qualified Streamly.Internal.Data.Stream.IsStream as S from this module as it is deprecated. and should use Stream.catRights here.

2022-12-01 09:41 UTC, harendra-kumar approved these changes

2022-12-01 09:41 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Stream/Top.hs
> +--import Streamly.Internal.Data.Stream (Stream, rights, fromStreamD, toStreamD)
```suggestion
```

2022-12-01 10:58 UTC, merged