Release Data.Array.Generic.Mut
composewell/streamly pull request #2161
Opened 2022-12-07 10:09 UTC by rnjtranjan

2022-12-08 19:14 UTC, harendra-kumar requested changes

2022-12-08 19:14 UTC, harendra-kumar commented on core/src/Streamly/Data/Array/Generic/Mut.hs
> +      Array (..)
Do not expose the constructor.

2022-12-08 19:14 UTC, harendra-kumar commented on core/src/Streamly/Data/Array/Generic/Mut.hs
> +    , newArray
The names in this module should be consistent with names in Streamly.Data.Array/Streamly.Data.Array.Mut .

2022-12-08 19:14 UTC, harendra-kumar commented on core/src/Streamly/Data/Array/Generic/Mut.hs
> +    , writeNUnsafe
Do not expose everything from the internal module. Please see what is exposed from other array modules and expose only carefully reviewed APIs that are consistent across all array modules.

2022-12-10 18:21 UTC, harendra-kumar requested changes
Can we keep the haddock headings consistent with Data.Array.Mut?
Export reader.

2022-12-10 18:21 UTC, harendra-kumar commented on core/src/Streamly/Data/Array/Generic/Mut.hs
> +    , getIndex
Not consistent with the API in Data.Array.Mut.

2022-12-11 08:24 UTC, rnjtranjan commented
Fix:https://github.com/composewell/streamly/issues/2083

2022-12-11 21:28 UTC, merged