Export the Tee type via Data.Fold
composewell/streamly pull request #2166
Opened 2022-12-09 09:14 UTC by rnjtranjan

2022-12-09 09:14 UTC, rnjtranjan commented
Fix:https://github.com/composewell/streamly/issues/2154

2022-12-10 19:08 UTC, harendra-kumar requested changes

2022-12-10 19:08 UTC, harendra-kumar commented on core/src/Streamly/Data/Fold/Tee.hs
> +{-# OPTIONS_GHC -Wno-deprecations #-}
This should not be needed.

2022-12-10 19:08 UTC, harendra-kumar commented on core/src/Streamly/Data/Fold/Tee.hs
> ---
We should note remove this.

2022-12-10 19:08 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Fold/Tee.hs
> +{-# DEPRECATED "Please use \"Streamly.Internal.Data.Fold\" instead." #-}
Do not deprecate this. Just import this module in Streamly.Data.Fold.

2022-12-26 09:26 UTC, harendra-kumar requested changes

2022-12-26 09:26 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Fold/Tee.hs
> +--
Move the documentation to the Tee type so that it is visible to users.

2022-12-27 08:37 UTC, harendra-kumar approved these changes

2022-12-27 08:39 UTC, merged