Fix dev flag build, test, benchmarks issues
composewell/streamly pull request #2206
Opened 2023-01-03 11:02 UTC by rnjtranjan

2023-01-03 12:28 UTC, rnjtranjan commented
Fixes:https://github.com/composewell/streamly/issues/2202

2023-01-04 07:34 UTC, harendra-kumar requested changes

2023-01-04 07:34 UTC, harendra-kumar commented on test/Streamly/Test/Data/Stream/Concurrent.hs
> +        Stream.fold Fold.toList (f [x4, f [x3, f ls21]])
Right or left associative tests apply to only binary operations like `append`, they do not apply to list flattening operations. If we really want to test these then we can test these on on `append2`, `parallel2` etc.

2023-01-04 07:34 UTC, harendra-kumar commented on test/Streamly/Test/Prelude/Serial.hs
> +    IS.fromStreamD $ D.splitOnSuffixSeq False patt f (IS.toStreamD m)
We should not use StreamD here, it is an internal module. Why not use the takeEndBySeq/takeEndBySeq_ folds?

2023-01-04 07:34 UTC, harendra-kumar commented on test/Streamly/Test/Prelude/Serial.hs
> +groupsBy cmp f m = IS.fromStreamD $ D.groupsBy cmp f (IS.toStreamD m)
Don't use StreamD. Why not use groupBy parser?

2023-01-04 07:34 UTC, harendra-kumar commented on test/Streamly/Test/Prelude/Serial.hs
> +groupsByRolling cmp f m =  IS.fromStreamD $ D.groupsRollingBy cmp f (IS.toStreamD m)
Don't use StreamD. Why not use groupByRolling parser?

2023-01-04 07:34 UTC, harendra-kumar commented on test/Streamly/Test/Prelude/Serial.hs
> +mapM'_ f = S.fold (FL.drainBy f)
Use `drainMapM` instead?

2023-01-04 07:34 UTC, harendra-kumar commented on test/Streamly/Test/Prelude/Serial.hs
> +mapM'_ f = S.fold (FL.drainBy f)
We can rename `mapM'_ ` also to drainMapM.

2023-01-04 07:34 UTC, harendra-kumar commented on test/Streamly/Test/Prelude/Serial.hs
> +            $ D.splitOnSeq (A.fromList ys) FL.toList (IS.toStreamD (S.fromList xs))
Do not use StreamD, use takeEndBySeq/_ fold instead.

2023-01-04 07:34 UTC, harendra-kumar commented on test/Streamly/Test/Prelude/Serial.hs
> +                liftIO $ toList
Why not use `liftIO` in toList/Splitter etc or just make their signature polymorphic.

2023-01-04 07:34 UTC, harendra-kumar commented on test/Streamly/Test/Prelude/Serial.hs
> +    ls <- run $ toList $ unfold0' unf
Since there is no unfold0 operation to test we can just remove this test.

2023-01-04 07:34 UTC, harendra-kumar commented on test/Streamly/Test/Prelude/Serial.hs
> +import qualified Streamly.Internal.Data.Stream.Concurrent as Concur
import as `S` instead, should be same as Stream.Prelude.

2023-01-04 07:34 UTC, harendra-kumar commented on test/Streamly/Test/Prelude/Serial.hs
> +       -- serialOps $ prop "serially (|:)" . constructWithConsM (S.|:) id
Can remove these.

2023-01-04 07:34 UTC, harendra-kumar commented on test/Streamly/Test/Prelude/Serial.hs
> +            toList (IS.concatMapWith g S.fromList (S.fromList inp))
concatPairsWith was renamed to `mergeMapWith`, so we should use that here.

2023-01-07 08:47 UTC, rnjtranjan reviewed
Looks good.

2023-01-07 09:02 UTC, merged