Use ParserK explicitly
composewell/streamly pull request #2270
Opened 2023-02-17 09:48 UTC by rnjtranjan

2023-02-17 09:48 UTC, rnjtranjan commented
Fixes:https://github.com/composewell/streamly/issues/2257

2023-02-18 01:49 UTC, harendra-kumar requested changes

2023-02-18 01:49 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Parser/ParserK/Type.hs
> +--type ParserK = Parser
Can remove this.

2023-02-18 01:49 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Stream/StreamK.hs
> +    => ParserK.ParserK a m b
Use the type unqualified.

2023-02-20 16:27 UTC, adithyaov approved these changes
Ah, I expected more changes for parser. Nice. There were only a few.

2023-03-02 08:28 UTC, harendra-kumar approved these changes

2023-03-02 08:29 UTC, merged