Rename chunksOf and arraysOf
composewell/streamly pull request #2271
Opened 2023-02-20 05:20 UTC by rnjtranjan

2023-02-20 11:22 UTC, rnjtranjan commented
Fixes:https://github.com/composewell/streamly/issues/2249

2023-03-02 04:14 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Fold.hs
> +    , foldChunksOf
We can use the name `groupsOf` instead.

2023-03-02 04:27 UTC, harendra-kumar reviewed
Since chunksOf is a released API, let's deprecate it and add `groupsOf` instead. keep ararysOf as it is for now, it is an internal API.

2023-03-02 12:59 UTC, harendra-kumar commented on core/src/Streamly/Data/Fold.hs
> +    , groupsOf
chunksOf cannot be removed, it should be deprecated.

2023-03-02 17:17 UTC, adithyaov commented on core/src/Streamly/Internal/Data/Array/Mut/Stream.hs
> -
Add this line back.

2023-03-02 17:18 UTC, adithyaov commented on core/src/Streamly/Internal/Data/Array/Mut/Type.hs
> --- arraysOf n = D.foldMany (writeN n)
Why remove this?

2023-03-02 17:19 UTC, adithyaov commented on core/src/Streamly/Internal/Data/Stream/Chunked.hs
> +-- > arraysOf n = Stream.arraysOf n (Array.writeN n)
Shouldn't this be `groupsOf`?

2023-03-02 17:21 UTC, adithyaov commented on core/src/Streamly/Internal/FileSystem/Handle.hs
> +-- XXX Maybe we should have a Fold.groupsOf like we have Stream.groupsOf
This should not be changed? `arraysOf` and `groupsOf` is different?

2023-03-02 17:21 UTC, adithyaov commented on src/Streamly/Internal/Data/Stream/IsStream/Reduce.hs
> +-- >>> Stream.toList $ Stream.arraysOf 2 Fold.sum (Stream.enumerateFromTo 1 10)
Shouldn't this be `groupsOf`?

2023-03-02 17:21 UTC, adithyaov requested changes
Some comments.

2023-03-03 08:20 UTC, adithyaov commented
https://github.com/composewell/streamly/issues/2292

2023-03-03 08:21 UTC, adithyaov commented on benchmark/Streamly/Benchmark/FileSystem/Handle/Read.hs
> +chunksOf n inh =
See https://github.com/composewell/streamly/issues/2292

2023-03-03 08:23 UTC, adithyaov commented on benchmark/Streamly/Benchmark/FileSystem/Handle/Read.hs
> +        -- chunksOf may use a different impl than groupsOf
This comment is incorrect.

2023-03-03 09:08 UTC, adithyaov commented
See https://github.com/composewell/streamly/pull/2293

2023-03-03 09:27 UTC, adithyaov commented
See https://github.com/composewell/streamly/pull/2293

2023-03-03 09:27 UTC, closed without merging