Expose groupsOf from Data.Stream
composewell/streamly pull request #2372
Opened 2023-03-20 08:10 UTC by rnjtranjan

2023-03-20 08:11 UTC, rnjtranjan commented
Fixes:https://github.com/composewell/streamly/issues/2359

2023-05-16 09:08 UTC, harendra-kumar requested changes
The checklist for exposing is: it has documentation (mandatory) and preferably tests, and benchmarks as well. This one does not have any docs. We can copy the docs from previous name of this i.e. `chunksOf` in Streamly.Prelude.

2023-05-22 14:35 UTC, harendra-kumar requested changes

2023-05-22 14:35 UTC, harendra-kumar commented on hie.yaml
> +              component: "test:Data.Array"
Should it be Data.Stream instead?

2023-05-22 14:35 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Stream/StreamD/Type.hs
> +-- @since 0.9.0
remove this line.

2023-05-22 14:35 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Stream/StreamD/Type.hs
> +-- @groupsOf n f = foldMany (FL.take n f)@
Put this under doctest comments.

2023-05-30 15:33 UTC, harendra-kumar requested changes

2023-05-30 15:33 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Stream/StreamD/Type.hs
> +-- @since 0.9.0
```suggestion
```

2023-05-30 15:33 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Stream/StreamD/Type.hs
> +-- | @groupsOf n f = foldMany (FL.take n f)@
Can you check this doc in haddock?

2023-07-04 17:37 UTC, merged