Remove pre-release annotation from some of the modules
composewell/streamly pull request #2411
Opened 2023-05-27 06:50 UTC by rnjtranjan

2023-05-27 15:44 UTC, harendra-kumar requested changes

2023-05-27 15:44 UTC, harendra-kumar commented on src/Streamly/Internal/FileSystem/Event.hs
> --- Stability   : pre-release
This should remain pre-release.

2023-05-27 15:44 UTC, harendra-kumar commented on src/Streamly/Internal/FileSystem/Event/Darwin.hs
> --- Stability   : pre-release
This should remain pre-release.

2023-05-27 15:44 UTC, harendra-kumar commented on src/Streamly/Internal/FileSystem/Event/Windows.hs
> --- Stability   : pre-release
This should remain pre-release.

2023-05-31 11:42 UTC, rnjtranjan commented
Fixes: https://github.com/composewell/streamly/issues/2409

2023-07-04 17:00 UTC, merged