Rename Internal.Data.Stream.StreamD to Internal.Data.Stream
composewell/streamly pull request #2428
Opened 2023-07-14 06:14 UTC by rnjtranjan

2023-07-14 06:15 UTC, rnjtranjan commented
Fixes:https://github.com/composewell/streamly/issues/2361

2023-07-21 17:31 UTC, harendra-kumar requested changes
We should keep Streamly.Internal.Data.Stream.StreamD as well but deprecate it. We can just export Stream.Internal.Data.Stream from it.

2023-07-21 17:31 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Stream/StreamD.hs
> --- |
We can deprecate this module and export Streamly.Internal.Data.Stream from it. So that if anyone has imported this, it continues working.

2023-07-21 17:31 UTC, harendra-kumar commented on docs/User/Project/Upgrading.md
> +(in Streamly.Internal.Data.StreamK) could be used to overcome the
This guide is to upgrade from 0.8 to 0.9, therefore, should not reflect changes in 0.10 .

2023-07-22 18:41 UTC, merged