Change the signature of "handle"
composewell/streamly pull request #2487
Opened 2023-08-01 13:07 UTC by rnjtranjan

2023-08-01 13:09 UTC, rnjtranjan commented
Fix:https://github.com/composewell/streamly/issues/2485

2023-08-01 22:00 UTC, harendra-kumar requested changes

2023-08-01 22:00 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Stream/StreamD/Exception.hs
> +                    $ Skip (GBracketException strm)
Collapse the two lines in a single line.

2023-08-01 22:00 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Stream/StreamD/Exception.hs
> +        (\a (e :: SomeException) _ -> return $ nilM (aft a >> MC.throwM e))
Same as previous comment.

2023-08-02 10:19 UTC, harendra-kumar requested changes
write a changelog entry for breaking change.

2023-08-02 14:14 UTC, harendra-kumar approved these changes

2023-08-02 14:30 UTC, merged