Expose setup stanza
composewell/streamly pull request #2493
Opened 2023-08-03 07:33 UTC by rnjtranjan

2023-08-03 11:22 UTC, rnjtranjan commented
Fix:https://github.com/composewell/streamly/issues/2051

2023-08-03 17:45 UTC, harendra-kumar requested changes
Need to include the same setup stanza in corresponding released modules as well. Otherwise there is not much use of this.

2023-08-03 17:45 UTC, harendra-kumar commented on core/src/DocTestDataFileSystem.hs
> +>>> import qualified Streamly.Data.Stream as Stream
Sort the modules.

2023-08-03 17:45 UTC, harendra-kumar commented on core/src/DocTestDataUnicode.hs
> +>>> import qualified Streamly.Unicode.Parser as Unicode
Separate non-internal imports from internal ones. Add a comment before internal imports - see Streamly.Data.Stream.

2023-08-05 14:23 UTC, harendra-kumar requested changes
Need to include the same setup stanza in corresponding released modules as well. Otherwise there is not much use of this.

2023-08-05 14:23 UTC, harendra-kumar commented on core/src/DocTestDataUnicode.hs
> +>>> import qualified Streamly.Unicode.Parser as Unicode
Do this in other modules as well.

2023-08-08 20:22 UTC, harendra-kumar reviewed
1. We need this only for exposed modules.
2. We should not combine setup of multiple exposed modules together.

2023-08-09 17:39 UTC, merged