Move StreamK and StreamD folder up
composewell/streamly pull request #2543
Opened 2023-08-18 03:47 UTC by rnjtranjan

2023-08-18 07:12 UTC, rnjtranjan commented
Fixes:https://github.com/composewell/streamly/issues/2477

2023-08-18 08:50 UTC, rnjtranjan commented
Fixes:https://github.com/composewell/streamly/issues/1666

2023-08-18 10:40 UTC, harendra-kumar requested changes
We should deprecate this core/src/Streamly/Internal/Data/Stream/StreamD.hs rather than deleting it - in case someone is importing from it.

2023-08-18 10:40 UTC, harendra-kumar commented on core/src/Streamly/Data/Stream.hs
> +    -- See also: "Streamly.Internal.Data.Stream.Eliminate" for @Pre-release@
This is hidden.

2023-08-18 10:40 UTC, harendra-kumar commented on core/src/Streamly/Data/Stream.hs
> +    -- See also: "Streamly.Internal.Data.Stream.Transform" for
This is hidden.

2023-08-18 10:40 UTC, harendra-kumar commented on core/src/Streamly/Data/Stream.hs
> +    -- See also: "Streamly.Internal.Data.Stream.Exception" for
This is hidden.

2023-08-18 10:40 UTC, harendra-kumar commented on core/streamly-core.cabal
> +                     , Streamly.Internal.Data.Stream.Common
Modules are listed in dependency order, lower level modules come before higher level ones. This should be before Data.Stream.

2023-08-19 10:07 UTC, harendra-kumar approved these changes

2023-08-19 10:08 UTC, merged