Add File internals that work directly with Path
composewell/streamly pull request #2869
Opened 2024-10-15 08:28 UTC by adithyaov

2024-11-04 10:25 UTC, adithyaov commented
Ensure the change made is tested in the CIs

2024-11-12 18:36 UTC, harendra-kumar requested changes
Change the module names as follows:

```
FileSystem.Windows.File => FileSystem.File.Window
FileSystem.Posix.File => FileSystem.File.Posix
```

2025-04-23 19:10 UTC, adithyaov commented on core/src/Streamly/Internal/FileSystem/FileIO.hs
> +    -- * Deprecated
You can remove this section, as this is a new module.

2025-04-23 19:17 UTC, adithyaov commented on core/src/Streamly/Internal/FileSystem/Posix/File.hsc
> +{-
Can we even comment CPP definitions?

2025-04-23 19:18 UTC, adithyaov commented on core/src/Streamly/Internal/FileSystem/Posix/File.hsc
> +##define MK_MODE_API(name1,name2,x) \
Is it `##define` and not `#define` because of `hsc`?

2025-04-23 19:49 UTC, adithyaov reviewed
I've reviewed the PR. I've added some comments.

2025-04-24 05:59 UTC, harendra-kumar commented on core/src/Streamly/Internal/FileSystem/FileIO.hs
> +    -- * Deprecated
I though it will be easier to replace the module if we keep them. But we can remove it too, because if someone is anyway making changes then they can change this as well.

2025-04-24 05:59 UTC, harendra-kumar commented on core/src/Streamly/Internal/FileSystem/Posix/File.hsc
> +##define MK_MODE_API(name1,name2,x) \
Yes, it was failing with an error and ##define worked.

2025-04-24 05:59 UTC, harendra-kumar commented on core/src/Streamly/Internal/FileSystem/Posix/File.hsc
> +name2 (FileMode mode) = FileMode (x .|. mode)
Yes, that's a bug. copy, paste and forgot to fix.

2025-04-24 05:59 UTC, harendra-kumar commented on core/src/Streamly/Internal/FileSystem/Posix/File.hsc
> +{-
No, we are using the definitions directly from the header files rather than defining ourselves. I kept this code commented, just in case there is any issue in using the headers directly.

2025-04-24 07:42 UTC, adithyaov commented on core/src/Streamly/Internal/FileSystem/Posix/File.hsc
> +{-
But if it did not error out because you've not used `##` it likely works as expected.

2025-04-27 04:32 UTC, harendra-kumar commented on core/src/Streamly/Internal/FileSystem/Posix/File.hsc
> +{-
This code is actually commented, it does not work in any way.

2025-04-30 05:39 UTC, merged