Fix the enum instance for IOSubSystem
composewell/streamly pull request #2890
Opened 2024-12-04 10:03 UTC by adithyaov

2024-12-04 10:04 UTC, adithyaov commented
See: https://hackage.haskell.org/package/ghc-internal-9.1001.0/docs/src/GHC.Internal.RTS.Flags.html#IoSubSystem

2024-12-04 18:01 UTC, harendra-kumar requested changes

2024-12-04 18:25 UTC, harendra-kumar requested changes
Fix hlint

2024-12-05 12:30 UTC, merged

2024-12-05 12:34 UTC, harendra-kumar commented
eqArray benchmarks have improved significantly. Can you check if the CPU time in these benchmarks has consistently increased:

```
All.Data.Fold/o-1-space.FileSplitSeq.takeEndBySeq_ infix empty pattern                               46617.80                     +74.58
All.Data.Fold/o-1-space.FileSplitSeq.takeEndBySeq_ suffix empty pattern                              46613.00                     +73.88
All.Data.Fold/o-1-space.FileSplitSeq.takeEndBySeq_ infix a                                           54333.50                     +56.68
All.Data.Fold/o-1-space.FileSplitSeq.takeEndBySeq_ infix lf                                          56050.60                     +52.13
```