Make empty stream behavior of splitSepBySeq_ similar to splitSepBy_
composewell/streamly pull request #2912
Opened 2024-12-20 19:29 UTC by adithyaov

- [ ] Check the benchmarks

2024-12-28 11:38 UTC, adithyaov commented on test/Streamly/Test/Data/Stream.hs
> +    -- implementation is not different.
```suggestion
    -- implementation is different.
```

2024-12-30 18:05 UTC, harendra-kumar reviewed
Can add some doctests in `splitSepBySeq_` and `splitEndBySeq` similar to splitSepBy_ ? Also enable the doctests in `splitBeginBy_`.

2025-01-02 09:37 UTC, adithyaov commented
> Also enable the doctests in splitBeginBy_.
`splitBeginBy` is undefined.

2025-01-06 12:51 UTC, harendra-kumar requested changes
Keep only interesting and minimal doctests for understanding the behavior. Move the rest to actual tests.

2025-01-06 12:51 UTC, harendra-kumar commented on core/src/Streamly/Internal/Data/Stream/Nesting.hs
> +            Stop -> final fs >> pure Stop
See splitSepBy_ . We should have the same behavior. If we have not consumed any element we should not initialize the fold. We will be perform initialization and finalization unnecessarily.

2025-01-06 22:40 UTC, harendra-kumar approved these changes

2025-01-07 11:52 UTC, merged