Add benchmarks to all the unfold combinators
composewell/streamly pull request #721
Opened 2020-10-19 02:30 UTC by adithyaov

2020-10-20 15:22 UTC, harendra-kumar requested changes

2020-10-20 15:22 UTC, harendra-kumar commented on benchmark/Streamly/Benchmark/Data/Unfold.hs
> +o_1_space_generation_specialized size =
We can have a single benchmark group for "generation" like we have in streams.

2020-10-20 15:22 UTC, harendra-kumar commented on benchmark/Streamly/Benchmark/Data/Unfold.hs
> +          -- , benchIO "fromStreamD" $ fromStreamD size
I guess this is just going to remain quadratic, we can have this benchmark run for a smaller stream size e.g. "fromStreamD (n/100)" or something like that and remove the `XXX` comment.

2020-10-20 15:22 UTC, harendra-kumar commented on benchmark/Streamly/Benchmark/Data/Unfold.hs
> +o_1_space_combination size =
We can call this `o_1_space_zip`, zip is always a separate class in all other benchmarks.

2020-10-20 15:22 UTC, harendra-kumar commented on benchmark/Streamly/Benchmark/Data/Unfold.hs
> +-- is implemented.
If this is expected, this should not be a `XXX` comment.

2020-10-20 15:22 UTC, harendra-kumar commented on benchmark/Streamly/Benchmark/Data/Unfold.hs
> +          , benchIO "takeWhileM" $ takeWhileM size
We can make a `o_1_space_filtering` group for all filtering ops, like we have in serial stream benchmarks.

2020-10-20 15:22 UTC, harendra-kumar commented on benchmark/Streamly/Benchmark/Data/Unfold.hs
> +
Add a section header here to demarcate the "Filtering" section.

2020-10-20 23:57 UTC, adithyaov commented on benchmark/Streamly/Benchmark/Data/Unfold.hs
> +    src2 = UF.take size (UF.supplySecond UF.enumerateFromStepIntegral 2)
Oh yeah, don't know why I did this. But the benchmarks don't seem to care anyway.

2020-10-21 00:00 UTC, adithyaov commented on benchmark/Streamly/Benchmark/Data/Unfold.hs
> +        1
I'm benchmarking `supplyFirst`. Need the seed to be `(a, b)`. I could do an `lmap` I guess.

2020-10-23 04:58 UTC, adithyaov commented on benchmark/Streamly/Benchmark/Data/Unfold.hs
> +        1
We can leave it like such for now.

2020-10-23 04:59 UTC, adithyaov commented on benchmark/Streamly/Benchmark/Data/Unfold.hs
> +    drainTransformationDefault size (UF.filter (\_ -> True)) start
We can leave it like this for now. This is shorter than `Prelude.const`

2020-10-23 05:01 UTC, adithyaov commented on benchmark/Streamly/Benchmark/Data/Unfold.hs
> +            $ UF.lmap (\() -> undefined)
We can do this, but probably in another set of changes. After this and #722 is merged

2020-10-23 06:04 UTC, adithyaov commented
This does not the changes of `iterateM` yet. Once this is approved, the batch PR will have the required changes.

2020-10-23 13:41 UTC, harendra-kumar approved these changes

2020-10-23 13:41 UTC, harendra-kumar commented on benchmark/Streamly/Benchmark/Data/Unfold.hs
> +            $ UF.lmap (\() -> undefined)
Can we raise an issue so that we do not lose this?

2020-10-23 14:11 UTC, adithyaov commented
See #735

2020-10-23 14:11 UTC, closed without merging