All the remaining unfold tests
composewell/streamly pull request #722
Opened 2020-10-20 01:50 UTC by adithyaov

Closes #609

2020-10-20 18:18 UTC, harendra-kumar requested changes
Mostly nitpicks, only `iterateM` needs a significant change.

2020-10-21 00:07 UTC, adithyaov commented on test/Streamly/Test/Data/Unfold.hs
> +lmap = True
This should have been removed.

2020-10-23 13:52 UTC, harendra-kumar approved these changes

2020-10-23 14:11 UTC, adithyaov commented
See #735

2020-10-23 14:11 UTC, closed without merging