add support for range based File reading/writing APIs
composewell/streamly pull request #764
Opened 2020-11-11 16:13 UTC by rnjtranjan

2020-11-11 16:13 UTC, rnjtranjan commented
fix #662

2020-11-12 03:47 UTC, adithyaov commented on src/Streamly/Internal/FileSystem/Handle.hs
> +import System.IO ( Handle
Maybe change this to,
```
import System.IO
       (Handle, SeekMode(..), hGetBufSome, hPutBuf, hSeek, stdin, stdout)
```

2020-11-12 03:49 UTC, adithyaov commented on src/Streamly/Internal/FileSystem/Handle.hs
> +  where
Indent `where` by 4 and add a new line.
So something like,
```
toChunksWithBufferOfRange size lenRef h = D.fromStreamD (D.Stream step ())
    where

    {-# INLINE_LATE step #-}
    ...
```

2020-11-12 03:50 UTC, adithyaov commented on src/Streamly/Internal/FileSystem/Handle.hs
> +toChunksWithBufferOfRange
I think you've missed an inline pragma here

2020-11-12 03:52 UTC, adithyaov commented on src/Streamly/Internal/FileSystem/Handle.hs
> +    S.mapM_ (\arr -> do
You can probably take this function out into a where clause and rewrite this as `S.mapM_ func`

2020-11-12 03:52 UTC, adithyaov commented on src/Streamly/Internal/FileSystem/Handle.hs
> +fromChunksWith h lenRef = do
I think you can omit this `do` keyword.

2021-01-04 09:25 UTC, adithyaov commented on src/Streamly/Internal/FileSystem/Handle.hs
> +fromChunksWith h lenRef = S.mapM_ func
Maybe rename `func` to something more informative?

2021-01-04 09:26 UTC, adithyaov commented on src/Streamly/Internal/FileSystem/Handle.hs
> +    func = \arr -> do
You can replace this with `func arr`

2021-07-30 12:12 UTC, harendra-kumar commented
Rebased.

2021-08-10 00:20 UTC, harendra-kumar commented
We need to implement only unfolds for this. Please implement the signature of unfold that I added in #1189.

2021-09-05 01:04 UTC, harendra-kumar requested changes

2021-09-05 08:16 UTC, rnjtranjan commented on src/Streamly/Internal/FileSystem/Handle.hs
>      Unfold m (Int, Int, Int, Handle) (Array Word8)
It goes beyond 80 columns.

2021-09-05 08:30 UTC, harendra-kumar requested changes

2021-09-05 08:30 UTC, harendra-kumar commented on src/Streamly/Internal/FileSystem/Handle.hs
> +        then return D.Stop -- if range is unsafe return empty stream
The code is obvious so we can remove the comment.

2021-09-05 08:30 UTC, harendra-kumar commented on src/Streamly/Internal/FileSystem/Handle.hs
> +            arr <- getChunk buffSize h
We can make this `getChunk (min bufSize remaining) h`.

2021-09-05 08:30 UTC, harendra-kumar commented on src/Streamly/Internal/FileSystem/Handle.hs
> +                            (0, 0, h)
If we use `min` in `getChunk` then this should not occur. We can put a `error "Bug: ...` message here.

2021-09-05 09:38 UTC, harendra-kumar reviewed
We can add a test as well to establish the basic sanity of the API.

2021-09-05 09:38 UTC, harendra-kumar commented on src/Streamly/Internal/FileSystem/Handle.hs
> +                            error "Bug: ..."
I meant some message in place of `...`, e.g. ` error "Bug: readFromChunksFromToWith: array length more than expected`.

2021-09-05 14:02 UTC, harendra-kumar reviewed
All these tests are very similar. It should be possible to factor out the common code in a single function and pass different args to it for different test cases.

2021-09-09 14:28 UTC, rnjtranjan reviewed
Looks good.

2021-09-09 15:48 UTC, merged