Enhance the fold type to capture terminating folds
composewell/streamly pull request #777
Opened 2020-11-22 03:17 UTC by adithyaov

See #770 and #775 

The changes made are minimally required.
Only in a few places, I've corrected the variables.
In places where the entire function was refactored, I've taken the liberty of variable naming and indentation, completely different from the original. (I'll go over and reduce the diff)

2020-11-22 03:21 UTC, adithyaov commented on src/Streamly/Internal/Data/Fold.hs
> +
This is pretty ugly. Improve code.

2020-11-22 03:22 UTC, adithyaov commented on src/Streamly/Internal/Data/Fold.hs
> +                return
Rethink indentation, Unnecessary wastage of horizontal space.

2020-11-22 03:22 UTC, adithyaov commented on src/Streamly/Internal/Data/Fold.hs
> +        case Map.lookup k mp of
This is pretty ugly. Improve code.

2020-11-22 03:22 UTC, adithyaov commented on src/Streamly/Internal/Data/Fold.hs
> +        return $ DemuxingWithDefault ini Set.empty mp
This is pretty ugly. Improve code.

2020-11-22 03:23 UTC, adithyaov commented on src/Streamly/Internal/Data/Fold.hs
> +                    $ case res of
Rethink indentation

2020-11-22 03:24 UTC, adithyaov commented on src/Streamly/Internal/Data/Fold/Types.hs
> +duplicate ::
I don't think there is a way to write `duplicate` in a nice way.

2020-11-22 03:26 UTC, adithyaov commented on src/Streamly/Internal/Data/Fold/Types.hs
> +lsessionsOf n (Fold stepS initialS extractS) (Fold stepC initialC extractC) =
This code has been completely changed. The extension of the previous implementation is very buggy.

Read `XXX` above.

2020-11-22 03:28 UTC, adithyaov commented on src/Streamly/Internal/Data/Stream/StreamD/Type.hs
> +
extra line

2020-11-23 13:08 UTC, harendra-kumar requested changes
Submitting partial review.

2020-11-23 13:08 UTC, harendra-kumar commented on src/Streamly/Internal/Data/Parser/ParserD/Types.hs
> +                    FL.Done fb -> return $ Done n fb
Factor out `return`.

2020-11-23 15:10 UTC, harendra-kumar requested changes

2020-11-23 17:58 UTC, adithyaov commented on src/Streamly/Internal/Data/Fold.hs
>      Fold step initial extract
Why? The implementation and behaviour is correct. We might as well keep it.

2020-11-23 18:49 UTC, adithyaov commented on src/Streamly/Internal/Data/Fold.hs
> +                              else let bst1 = Set.insert k bst
We will probably need a state monad or an IORef to check the termination condition.

2020-11-23 19:01 UTC, adithyaov commented on src/Streamly/Internal/Data/Fold.hs
> +                              else let bst1 = Set.insert k bst
I'll change this after 671

2020-11-23 19:12 UTC, adithyaov commented on src/Streamly/Internal/Data/Fold/Types.hs
> +             in Fold step1 (return i) extract1
This is a bug.

2020-11-23 19:23 UTC, adithyaov commented on src/Streamly/Internal/Data/Fold.hs
> +        case Map.lookup k mp of
We will probably need a state monad or an IORef to check the termination condition if we use alterF.

2020-11-24 03:02 UTC, adithyaov commented
See #770

2020-11-24 03:02 UTC, closed without merging