Add test cases for Network.Socket module
composewell/streamly pull request #809
Opened 2020-12-06 19:04 UTC by rnjtranjan

2020-12-09 06:07 UTC, harendra-kumar reviewed
Its a good idea to open separate PRs for networking and Unicode tests, since they are unrelated modules.

2020-12-30 20:10 UTC, harendra-kumar requested changes
Please rebase and resolve the comments.

2020-12-30 20:10 UTC, harendra-kumar commented on test/Streamly/Test/Unicode/Stream.hs
> +            monadicIO $ do
4 space indent.

2020-12-31 09:21 UTC, rnjtranjan commented on test/Streamly/Test/Network/Inet/TCP.hs
> +    S.replicate 1 testDataLarge                        -- SerialT IO String
Not sure about comment "S.yield?" Pls elaborate.

2021-01-02 12:35 UTC, harendra-kumar commented on test/Streamly/Test/Network/Inet/TCP.hs
> +    S.replicate 1 testDataLarge                        -- SerialT IO String
`S.yield` = `S.replicate 1`.

2021-01-02 19:17 UTC, specdrake commented on test/Streamly/Test/Network/Socket.hs
> +-- Accept connecttions and handle connected sockets
there is a typo in `connections`

2021-01-03 22:35 UTC, merged