Add some parser combinators
composewell/streamly pull request #839
Opened 2020-12-14 12:58 UTC by specdrake

2020-12-17 13:53 UTC, harendra-kumar commented
Please use one PR per combinator. Do not add multiple in one. It is easier to review and merge a PR with a single combinator.

2020-12-17 13:54 UTC, harendra-kumar commented
Is this ready for review, the status says "Draft"?

2020-12-17 14:32 UTC, specdrake commented
> Please use one PR per combinator. Do not add multiple in one. It is easier to review and merge a PR with a single combinator.

Okay

2020-12-17 14:33 UTC, specdrake commented
> Is this ready for review, the status says "Draft"?

I was planning to add all the combinators in this PR, I'll separate them into multiple PRs and add its tests and benchmarks in the current PR.

2020-12-17 20:04 UTC, specdrake commented on src/Streamly/Internal/Data/Parser.hs
> +-- Stops after @m@ elements.
Yes, it should be `n`.

2020-12-17 20:04 UTC, specdrake commented on src/Streamly/Internal/Data/Parser.hs
> +-- Fails if the stream ends before @n@ elements could be taken.
Yes, I switched the too.

2020-12-29 15:00 UTC, harendra-kumar requested changes
Mostly good. Rebase it and take care of some nitpicks.

2020-12-29 19:39 UTC, specdrake commented on test/Streamly/Test/Data/Parser/ParserD.hs
> +takeBetweenPass =
Yes, I was thinking there are many duplicate tests.

2021-01-04 13:03 UTC, harendra-kumar commented
Merged offline.

2021-01-04 13:03 UTC, closed without merging