Add combinators for Timeout Buffered writer stream
composewell/streamly pull request #842
Opened 2020-12-18 17:32 UTC by rnjtranjan

With Timeout combinators 45,000,000  Bytes written to socket and then drained out in **142.4000** seconds vs **122.0099** secs without Timeout combinators.

2021-01-12 13:59 UTC, harendra-kumar requested changes
We also need corresponding APIs in the Handle/File modules, that could be a separate PR though. Handle module has benchmarks as well so we can see how it performs.

2021-01-12 13:59 UTC, harendra-kumar commented on src/Streamly/Internal/Network/Socket.hs
> +chunksOfTimeout n t =
1. This should go in the same module as `chunksOf`/`intervalsOf`. 
2. We could have a corresponding `chunksOf` as well (i.e. without a timeout), but we already have a `chunksOf`. So should we call these `justsOf` and `justsOfTimeout` to indicate contiguous chunks of `Just` values?

2021-09-16 11:39 UTC, rnjtranjan commented
a PR https://github.com/composewell/streamly/pull/1236 for FileHandle has been created.

2021-11-07 12:38 UTC, harendra-kumar reviewed
I am going to close this PR and create a new one as a replacement.

2021-11-07 12:38 UTC, harendra-kumar commented on src/Streamly/Internal/Data/Array/Foreign/Mut/Type.hs
> +    extract = liftIO . shrinkToFit
We should not be writing new custom combinators for this job. We can use existing fold/parse combinators.

2021-11-07 12:38 UTC, harendra-kumar commented on src/Streamly/Internal/Data/Stream/IsStream/Transform.hs
> +    . justsOf
As mentioned in #456 this has an undesired behavior. The timeout may occur after the span is emitted and the timeout would force eject a smaller span. Ideally we should reset the timer whenever we emit a span.

2021-11-07 12:39 UTC, harendra-kumar commented
Closing this, it should be implemented differently, I will create a new one.

2021-11-07 12:39 UTC, closed without merging