Rename foldMany and foldMany1
composewell/streamly pull request #923
Opened 2021-02-08 21:01 UTC by harendra-kumar

foldMany1 is the default foldMany now. foldMany is renamed to
foldManyPost which is of limited use to split in an infix manner.

2021-02-09 21:01 UTC, adithyaov requested changes
I see,
```
Like 'foldMany' except that...
```
in the documentation of `foldMany`.
Can you recheck the haddock documentation of `foldMany` and `foldManyPost`?

2021-02-09 21:18 UTC, harendra-kumar commented
That is in the doc of foldManyPost, not in foldMany.

2021-02-09 21:19 UTC, harendra-kumar commented
Ok, you are talking about the doc in StreamD/Type. Would have been easier if you had commented on the line.

2021-02-10 14:07 UTC, adithyaov approved these changes

2021-02-10 19:07 UTC, merged